// Code generated by ent, DO NOT EDIT.

package riskrule

import (
	"haruki-suite/utils/database/postgresql/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldLTE(FieldID, id))
}

// RuleKey applies equality check predicate on the "rule_key" field. It's identical to RuleKeyEQ.
func RuleKey(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEQ(FieldRuleKey, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEQ(FieldDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEQ(FieldUpdatedBy, v))
}

// RuleKeyEQ applies the EQ predicate on the "rule_key" field.
func RuleKeyEQ(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEQ(FieldRuleKey, v))
}

// RuleKeyNEQ applies the NEQ predicate on the "rule_key" field.
func RuleKeyNEQ(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNEQ(FieldRuleKey, v))
}

// RuleKeyIn applies the In predicate on the "rule_key" field.
func RuleKeyIn(vs ...string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldIn(FieldRuleKey, vs...))
}

// RuleKeyNotIn applies the NotIn predicate on the "rule_key" field.
func RuleKeyNotIn(vs ...string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNotIn(FieldRuleKey, vs...))
}

// RuleKeyGT applies the GT predicate on the "rule_key" field.
func RuleKeyGT(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldGT(FieldRuleKey, v))
}

// RuleKeyGTE applies the GTE predicate on the "rule_key" field.
func RuleKeyGTE(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldGTE(FieldRuleKey, v))
}

// RuleKeyLT applies the LT predicate on the "rule_key" field.
func RuleKeyLT(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldLT(FieldRuleKey, v))
}

// RuleKeyLTE applies the LTE predicate on the "rule_key" field.
func RuleKeyLTE(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldLTE(FieldRuleKey, v))
}

// RuleKeyContains applies the Contains predicate on the "rule_key" field.
func RuleKeyContains(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldContains(FieldRuleKey, v))
}

// RuleKeyHasPrefix applies the HasPrefix predicate on the "rule_key" field.
func RuleKeyHasPrefix(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldHasPrefix(FieldRuleKey, v))
}

// RuleKeyHasSuffix applies the HasSuffix predicate on the "rule_key" field.
func RuleKeyHasSuffix(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldHasSuffix(FieldRuleKey, v))
}

// RuleKeyEqualFold applies the EqualFold predicate on the "rule_key" field.
func RuleKeyEqualFold(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEqualFold(FieldRuleKey, v))
}

// RuleKeyContainsFold applies the ContainsFold predicate on the "rule_key" field.
func RuleKeyContainsFold(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldContainsFold(FieldRuleKey, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.RiskRule {
	return predicate.RiskRule(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldContainsFold(FieldDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.RiskRule {
	return predicate.RiskRule(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.RiskRule {
	return predicate.RiskRule(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.RiskRule {
	return predicate.RiskRule(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RiskRule) predicate.RiskRule {
	return predicate.RiskRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RiskRule) predicate.RiskRule {
	return predicate.RiskRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RiskRule) predicate.RiskRule {
	return predicate.RiskRule(sql.NotPredicates(p))
}
