from modules.mongo import MongoDBManager
from configs import MONGODB_DB_URL, MONGODB_DB, MYSEKAI_DB, SUITE_DB, WEBHOOK_USER_DB, WEBHOOK_USER_USER_DB

mongo = MongoDBManager(MONGODB_DB_URL, MONGODB_DB, SUITE_DB, MYSEKAI_DB, WEBHOOK_USER_DB, WEBHOOK_USER_USER_DB)
