package adminusers

const (
	contentTypeApplicationJSON           = "application/json"
	contentTypeApplicationFormURLEncoded = "application/x-www-form-urlencoded"
)

const (
	adminAuditTargetTypeUser = "user"
)

const (
	adminAuditActionUserBan           = "admin.user.ban"
	adminAuditActionUserUnban         = "admin.user.unban"
	adminAuditActionUserForceLogout   = "admin.user.force_logout"
	adminAuditActionUserSoftDelete    = "admin.user.soft_delete"
	adminAuditActionUserRestore       = "admin.user.restore"
	adminAuditActionUserResetPass     = "admin.user.reset_password"
	adminAuditActionUserRoleUpdate    = "admin.user.role.update"
	adminAuditActionUserBatchPrefix   = "admin.user.batch."
	adminAuditActionUserBatchRole     = "admin.user.batch.role.update"
	adminAuditActionUserBatchAllowCN  = "admin.user.batch.allow_cn_mysekai.update"
	adminAuditActionUserActivityQuery = "admin.user.activity.query"
	adminAuditActionUserOAuthList     = "admin.user.oauth.list"
	adminAuditActionUserOAuthRevoke   = "admin.user.oauth.revoke"

	adminAuditActionUserGameBindingsList  = "admin.user.game_account_bindings.list"
	adminAuditActionUserGameBindingUpsert = "admin.user.game_account_binding.upsert"
	adminAuditActionUserGameBindingDelete = "admin.user.game_account_binding.delete"
	adminAuditActionUserEmailUpdate       = "admin.user.email.update"
	adminAuditActionUserAllowCNUpdate     = "admin.user.allow_cn_mysekai.update"
	adminAuditActionUserSocialGet         = "admin.user.social_platform.get"
	adminAuditActionUserSocialUpsert      = "admin.user.social_platform.upsert"
	adminAuditActionUserSocialClear       = "admin.user.social_platform.clear"
	adminAuditActionUserAuthorizedList    = "admin.user.authorized_social_platforms.list"
	adminAuditActionUserAuthorizedUpsert  = "admin.user.authorized_social_platform.upsert"
	adminAuditActionUserAuthorizedDelete  = "admin.user.authorized_social_platform.delete"
	adminAuditActionUserIOSCodeRegenerate = "admin.user.ios_upload_code.regenerate"
	adminAuditActionUserIOSCodeClear      = "admin.user.ios_upload_code.clear"
)

const (
	adminBatchActionBan         = "ban"
	adminBatchActionUnban       = "unban"
	adminBatchActionForceLogout = "force_logout"
	adminBatchActionRoleUpdate  = "role_update"
	adminBatchActionAllowCN     = "allow_cn_mysekai_update"
)

const (
	adminFailureReasonInvalidRequestPayload                = "invalid_request_payload"
	adminFailureReasonMissingUserSession                   = "missing_user_session"
	adminFailureReasonTargetUserNotFound                   = "target_user_not_found"
	adminFailureReasonPermissionDenied                     = "permission_denied"
	adminFailureReasonQueryTargetUserFailed                = "query_target_user_failed"
	adminFailureReasonQueryClientFailed                    = "query_client_failed"
	adminFailureReasonMissingTargetUserID                  = "missing_target_user_id"
	adminFailureReasonClientNotFound                       = "client_not_found"
	adminFailureReasonInvalidQueryFilters                  = "invalid_query_filters"
	adminFailureReasonStartTransactionFailed               = "start_transaction_failed"
	adminFailureReasonCommitTransactionFailed              = "commit_transaction_failed"
	adminFailureReasonQueryBindingFailed                   = "query_binding_failed"
	adminFailureReasonBindingNotFound                      = "binding_not_found"
	adminFailureReasonAuthorizedSocialPlatformConflict     = "authorized_social_platform_conflict"
	adminFailureReasonAuthorizedSocialPlatformNotFound     = "authorized_social_platform_not_found"
	adminFailureReasonBanUserFailed                        = "ban_user_failed"
	adminFailureReasonBindingConflict                      = "binding_conflict"
	adminFailureReasonBindingOwnedByOtherUser              = "binding_owned_by_other_user"
	adminFailureReasonClearIosUploadCodeFailed             = "clear_ios_upload_code_failed"
	adminFailureReasonClearSessionsFailed                  = "clear_sessions_failed"
	adminFailureReasonClearSocialPlatformFailed            = "clear_social_platform_failed"
	adminFailureReasonCountSystemLogsFailed                = "count_system_logs_failed"
	adminFailureReasonCountUploadLogsFailed                = "count_upload_logs_failed"
	adminFailureReasonCountUploadSuccessFailed             = "count_upload_success_failed"
	adminFailureReasonCreateAuthorizedSocialPlatformFailed = "create_authorized_social_platform_failed"
	adminFailureReasonCreateBindingFailed                  = "create_binding_failed"
	adminFailureReasonCreateIosUploadCodeFailed            = "create_ios_upload_code_failed"
	adminFailureReasonCreateSocialPlatformFailed           = "create_social_platform_failed"
	adminFailureReasonDeleteAuthorizedSocialPlatformFailed = "delete_authorized_social_platform_failed"
	adminFailureReasonDeleteBindingFailed                  = "delete_binding_failed"
	adminFailureReasonEmailConflict                        = "email_conflict"
	adminFailureReasonGenerateTemporaryPasswordFailed      = "generate_temporary_password_failed"
	adminFailureReasonGenerateUploadCodeFailed             = "generate_upload_code_failed"
	adminFailureReasonHashPasswordFailed                   = "hash_password_failed"
	adminFailureReasonInvalidBanReason                     = "invalid_ban_reason"
	adminFailureReasonInvalidGameUserId                    = "invalid_game_user_id"
	adminFailureReasonInvalidIncludeRevoked                = "invalid_include_revoked"
	adminFailureReasonInvalidPassword                      = "invalid_password"
	adminFailureReasonInvalidPlatformId                    = "invalid_platform_id"
	adminFailureReasonInvalidReason                        = "invalid_reason"
	adminFailureReasonInvalidRole                          = "invalid_role"
	adminFailureReasonInvalidServer                        = "invalid_server"
	adminFailureReasonInvalidUserIds                       = "invalid_user_ids"
	adminFailureReasonIosUploadCodeConflict                = "ios_upload_code_conflict"
	adminFailureReasonMissingGameUserId                    = "missing_game_user_id"
	adminFailureReasonQueryAuthorizationsFailed            = "query_authorizations_failed"
	adminFailureReasonQueryAuthorizedSocialPlatformFailed  = "query_authorized_social_platform_failed"
	adminFailureReasonQueryAuthorizedSocialPlatformsFailed = "query_authorized_social_platforms_failed"
	adminFailureReasonQueryBindingsFailed                  = "query_bindings_failed"
	adminFailureReasonQueryConflictFailed                  = "query_conflict_failed"
	adminFailureReasonQueryIosUploadCodeFailed             = "query_ios_upload_code_failed"
	adminFailureReasonQuerySocialPlatformFailed            = "query_social_platform_failed"
	adminFailureReasonQuerySystemLogsFailed                = "query_system_logs_failed"
	adminFailureReasonQueryTokenStatsFailed                = "query_token_stats_failed"
	adminFailureReasonQueryUploadLogsFailed                = "query_upload_logs_failed"
	adminFailureReasonQueryUserConflictFailed              = "query_user_conflict_failed"
	adminFailureReasonRevokeAuthorizationsFailed           = "revoke_authorizations_failed"
	adminFailureReasonRevokeTokensFailed                   = "revoke_tokens_failed"
	adminFailureReasonSessionStoreUnavailable              = "session_store_unavailable"
	adminFailureReasonSocialPlatformConflict               = "social_platform_conflict"
	adminFailureReasonUnbanUserFailed                      = "unban_user_failed"
	adminFailureReasonUpdateAllowCnMysekaiFailed           = "update_allow_cn_mysekai_failed"
	adminFailureReasonUpdateAuthorizedSocialPlatformFailed = "update_authorized_social_platform_failed"
	adminFailureReasonUpdateBindingFailed                  = "update_binding_failed"
	adminFailureReasonUpdateIosUploadCodeFailed            = "update_ios_upload_code_failed"
	adminFailureReasonUpdatePasswordFailed                 = "update_password_failed"
	adminFailureReasonUpdateRoleFailed                     = "update_role_failed"
	adminFailureReasonUpdateSocialPlatformFailed           = "update_social_platform_failed"
	adminFailureReasonUpdateUserEmailFailed                = "update_user_email_failed"
	adminFailureReasonUpdateUserFailed                     = "update_user_failed"
)

const (
	adminBatchResultCodeUserNotFound    = "user_not_found"
	adminBatchResultCodeOperationFailed = "operation_failed"
)
