// Code generated by ent, DO NOT EDIT.

package uploadlog

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the uploadlog type in the database.
	Label = "upload_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldServer holds the string denoting the server field in the database.
	FieldServer = "server"
	// FieldGameUserID holds the string denoting the game_user_id field in the database.
	FieldGameUserID = "game_user_id"
	// FieldToolboxUserID holds the string denoting the toolbox_user_id field in the database.
	FieldToolboxUserID = "toolbox_user_id"
	// FieldDataType holds the string denoting the data_type field in the database.
	FieldDataType = "data_type"
	// FieldUploadMethod holds the string denoting the upload_method field in the database.
	FieldUploadMethod = "upload_method"
	// FieldSuccess holds the string denoting the success field in the database.
	FieldSuccess = "success"
	// FieldUploadTime holds the string denoting the upload_time field in the database.
	FieldUploadTime = "upload_time"
	// Table holds the table name of the uploadlog in the database.
	Table = "upload_logs"
)

// Columns holds all SQL columns for uploadlog fields.
var Columns = []string{
	FieldID,
	FieldServer,
	FieldGameUserID,
	FieldToolboxUserID,
	FieldDataType,
	FieldUploadMethod,
	FieldSuccess,
	FieldUploadTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// GameUserIDValidator is a validator for the "game_user_id" field. It is called by the builders before save.
	GameUserIDValidator func(string) error
	// ToolboxUserIDValidator is a validator for the "toolbox_user_id" field. It is called by the builders before save.
	ToolboxUserIDValidator func(string) error
)

// OrderOption defines the ordering options for the UploadLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByServer orders the results by the server field.
func ByServer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServer, opts...).ToFunc()
}

// ByGameUserID orders the results by the game_user_id field.
func ByGameUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGameUserID, opts...).ToFunc()
}

// ByToolboxUserID orders the results by the toolbox_user_id field.
func ByToolboxUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToolboxUserID, opts...).ToFunc()
}

// ByDataType orders the results by the data_type field.
func ByDataType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataType, opts...).ToFunc()
}

// ByUploadMethod orders the results by the upload_method field.
func ByUploadMethod(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadMethod, opts...).ToFunc()
}

// BySuccess orders the results by the success field.
func BySuccess(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuccess, opts...).ToFunc()
}

// ByUploadTime orders the results by the upload_time field.
func ByUploadTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadTime, opts...).ToFunc()
}
