// Code generated by ent, DO NOT EDIT.

package postgresql

import (
	"context"
	"haruki-suite/utils/database/postgresql/friendlink"
	"haruki-suite/utils/database/postgresql/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FriendLinkDelete is the builder for deleting a FriendLink entity.
type FriendLinkDelete struct {
	config
	hooks    []Hook
	mutation *FriendLinkMutation
}

// Where appends a list predicates to the FriendLinkDelete builder.
func (_d *FriendLinkDelete) Where(ps ...predicate.FriendLink) *FriendLinkDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *FriendLinkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FriendLinkDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *FriendLinkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(friendlink.Table, sqlgraph.NewFieldSpec(friendlink.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// FriendLinkDeleteOne is the builder for deleting a single FriendLink entity.
type FriendLinkDeleteOne struct {
	_d *FriendLinkDelete
}

// Where appends a list predicates to the FriendLinkDelete builder.
func (_d *FriendLinkDeleteOne) Where(ps ...predicate.FriendLink) *FriendLinkDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *FriendLinkDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{friendlink.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *FriendLinkDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
