// Code generated by ent, DO NOT EDIT.

package postgresql

import (
	"context"
	"errors"
	"fmt"
	"haruki-suite/entsrc/schema"
	"haruki-suite/utils/database/postgresql/gameaccountbinding"
	"haruki-suite/utils/database/postgresql/user"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GameAccountBindingCreate is the builder for creating a GameAccountBinding entity.
type GameAccountBindingCreate struct {
	config
	mutation *GameAccountBindingMutation
	hooks    []Hook
}

// SetServer sets the "server" field.
func (_c *GameAccountBindingCreate) SetServer(v string) *GameAccountBindingCreate {
	_c.mutation.SetServer(v)
	return _c
}

// SetGameUserID sets the "game_user_id" field.
func (_c *GameAccountBindingCreate) SetGameUserID(v string) *GameAccountBindingCreate {
	_c.mutation.SetGameUserID(v)
	return _c
}

// SetVerified sets the "verified" field.
func (_c *GameAccountBindingCreate) SetVerified(v bool) *GameAccountBindingCreate {
	_c.mutation.SetVerified(v)
	return _c
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (_c *GameAccountBindingCreate) SetNillableVerified(v *bool) *GameAccountBindingCreate {
	if v != nil {
		_c.SetVerified(*v)
	}
	return _c
}

// SetSuite sets the "suite" field.
func (_c *GameAccountBindingCreate) SetSuite(v *schema.SuiteDataPrivacySettings) *GameAccountBindingCreate {
	_c.mutation.SetSuite(v)
	return _c
}

// SetMysekai sets the "mysekai" field.
func (_c *GameAccountBindingCreate) SetMysekai(v *schema.MysekaiDataPrivacySettings) *GameAccountBindingCreate {
	_c.mutation.SetMysekai(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *GameAccountBindingCreate) SetUserID(id string) *GameAccountBindingCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *GameAccountBindingCreate) SetNillableUserID(id *string) *GameAccountBindingCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *GameAccountBindingCreate) SetUser(v *User) *GameAccountBindingCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the GameAccountBindingMutation object of the builder.
func (_c *GameAccountBindingCreate) Mutation() *GameAccountBindingMutation {
	return _c.mutation
}

// Save creates the GameAccountBinding in the database.
func (_c *GameAccountBindingCreate) Save(ctx context.Context) (*GameAccountBinding, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *GameAccountBindingCreate) SaveX(ctx context.Context) *GameAccountBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GameAccountBindingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GameAccountBindingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *GameAccountBindingCreate) defaults() {
	if _, ok := _c.mutation.Verified(); !ok {
		v := gameaccountbinding.DefaultVerified
		_c.mutation.SetVerified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *GameAccountBindingCreate) check() error {
	if _, ok := _c.mutation.Server(); !ok {
		return &ValidationError{Name: "server", err: errors.New(`postgresql: missing required field "GameAccountBinding.server"`)}
	}
	if _, ok := _c.mutation.GameUserID(); !ok {
		return &ValidationError{Name: "game_user_id", err: errors.New(`postgresql: missing required field "GameAccountBinding.game_user_id"`)}
	}
	if _, ok := _c.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`postgresql: missing required field "GameAccountBinding.verified"`)}
	}
	return nil
}

func (_c *GameAccountBindingCreate) sqlSave(ctx context.Context) (*GameAccountBinding, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *GameAccountBindingCreate) createSpec() (*GameAccountBinding, *sqlgraph.CreateSpec) {
	var (
		_node = &GameAccountBinding{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(gameaccountbinding.Table, sqlgraph.NewFieldSpec(gameaccountbinding.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Server(); ok {
		_spec.SetField(gameaccountbinding.FieldServer, field.TypeString, value)
		_node.Server = value
	}
	if value, ok := _c.mutation.GameUserID(); ok {
		_spec.SetField(gameaccountbinding.FieldGameUserID, field.TypeString, value)
		_node.GameUserID = value
	}
	if value, ok := _c.mutation.Verified(); ok {
		_spec.SetField(gameaccountbinding.FieldVerified, field.TypeBool, value)
		_node.Verified = value
	}
	if value, ok := _c.mutation.Suite(); ok {
		_spec.SetField(gameaccountbinding.FieldSuite, field.TypeJSON, value)
		_node.Suite = value
	}
	if value, ok := _c.mutation.Mysekai(); ok {
		_spec.SetField(gameaccountbinding.FieldMysekai, field.TypeJSON, value)
		_node.Mysekai = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   gameaccountbinding.UserTable,
			Columns: []string{gameaccountbinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_game_account_bindings = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// GameAccountBindingCreateBulk is the builder for creating many GameAccountBinding entities in bulk.
type GameAccountBindingCreateBulk struct {
	config
	err      error
	builders []*GameAccountBindingCreate
}

// Save creates the GameAccountBinding entities in the database.
func (_c *GameAccountBindingCreateBulk) Save(ctx context.Context) ([]*GameAccountBinding, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*GameAccountBinding, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*GameAccountBindingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *GameAccountBindingCreateBulk) SaveX(ctx context.Context) []*GameAccountBinding {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *GameAccountBindingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *GameAccountBindingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
