// Code generated by ent, DO NOT EDIT.

package postgresql

import (
	"context"
	"errors"
	"fmt"
	"haruki-suite/utils/database/postgresql/oauthclient"
	"haruki-suite/utils/database/postgresql/oauthtoken"
	"haruki-suite/utils/database/postgresql/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OAuthTokenCreate is the builder for creating a OAuthToken entity.
type OAuthTokenCreate struct {
	config
	mutation *OAuthTokenMutation
	hooks    []Hook
}

// SetAccessToken sets the "access_token" field.
func (_c *OAuthTokenCreate) SetAccessToken(v string) *OAuthTokenCreate {
	_c.mutation.SetAccessToken(v)
	return _c
}

// SetRefreshToken sets the "refresh_token" field.
func (_c *OAuthTokenCreate) SetRefreshToken(v string) *OAuthTokenCreate {
	_c.mutation.SetRefreshToken(v)
	return _c
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_c *OAuthTokenCreate) SetNillableRefreshToken(v *string) *OAuthTokenCreate {
	if v != nil {
		_c.SetRefreshToken(*v)
	}
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OAuthTokenCreate) SetScopes(v []string) *OAuthTokenCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *OAuthTokenCreate) SetExpiresAt(v time.Time) *OAuthTokenCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *OAuthTokenCreate) SetNillableExpiresAt(v *time.Time) *OAuthTokenCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetRevoked sets the "revoked" field.
func (_c *OAuthTokenCreate) SetRevoked(v bool) *OAuthTokenCreate {
	_c.mutation.SetRevoked(v)
	return _c
}

// SetNillableRevoked sets the "revoked" field if the given value is not nil.
func (_c *OAuthTokenCreate) SetNillableRevoked(v *bool) *OAuthTokenCreate {
	if v != nil {
		_c.SetRevoked(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthTokenCreate) SetCreatedAt(v time.Time) *OAuthTokenCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthTokenCreate) SetNillableCreatedAt(v *time.Time) *OAuthTokenCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *OAuthTokenCreate) SetUserID(id string) *OAuthTokenCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *OAuthTokenCreate) SetUser(v *User) *OAuthTokenCreate {
	return _c.SetUserID(v.ID)
}

// SetClientID sets the "client" edge to the OAuthClient entity by ID.
func (_c *OAuthTokenCreate) SetClientID(id int) *OAuthTokenCreate {
	_c.mutation.SetClientID(id)
	return _c
}

// SetClient sets the "client" edge to the OAuthClient entity.
func (_c *OAuthTokenCreate) SetClient(v *OAuthClient) *OAuthTokenCreate {
	return _c.SetClientID(v.ID)
}

// Mutation returns the OAuthTokenMutation object of the builder.
func (_c *OAuthTokenCreate) Mutation() *OAuthTokenMutation {
	return _c.mutation
}

// Save creates the OAuthToken in the database.
func (_c *OAuthTokenCreate) Save(ctx context.Context) (*OAuthToken, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthTokenCreate) SaveX(ctx context.Context) *OAuthToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthTokenCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthTokenCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthTokenCreate) defaults() {
	if _, ok := _c.mutation.Revoked(); !ok {
		v := oauthtoken.DefaultRevoked
		_c.mutation.SetRevoked(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthtoken.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthTokenCreate) check() error {
	if _, ok := _c.mutation.AccessToken(); !ok {
		return &ValidationError{Name: "access_token", err: errors.New(`postgresql: missing required field "OAuthToken.access_token"`)}
	}
	if v, ok := _c.mutation.AccessToken(); ok {
		if err := oauthtoken.AccessTokenValidator(v); err != nil {
			return &ValidationError{Name: "access_token", err: fmt.Errorf(`postgresql: validator failed for field "OAuthToken.access_token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`postgresql: missing required field "OAuthToken.scopes"`)}
	}
	if _, ok := _c.mutation.Revoked(); !ok {
		return &ValidationError{Name: "revoked", err: errors.New(`postgresql: missing required field "OAuthToken.revoked"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`postgresql: missing required field "OAuthToken.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`postgresql: missing required edge "OAuthToken.user"`)}
	}
	if len(_c.mutation.ClientIDs()) == 0 {
		return &ValidationError{Name: "client", err: errors.New(`postgresql: missing required edge "OAuthToken.client"`)}
	}
	return nil
}

func (_c *OAuthTokenCreate) sqlSave(ctx context.Context) (*OAuthToken, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthTokenCreate) createSpec() (*OAuthToken, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthToken{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthtoken.Table, sqlgraph.NewFieldSpec(oauthtoken.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.AccessToken(); ok {
		_spec.SetField(oauthtoken.FieldAccessToken, field.TypeString, value)
		_node.AccessToken = value
	}
	if value, ok := _c.mutation.RefreshToken(); ok {
		_spec.SetField(oauthtoken.FieldRefreshToken, field.TypeString, value)
		_node.RefreshToken = &value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthtoken.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(oauthtoken.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if value, ok := _c.mutation.Revoked(); ok {
		_spec.SetField(oauthtoken.FieldRevoked, field.TypeBool, value)
		_node.Revoked = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthtoken.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthtoken.UserTable,
			Columns: []string{oauthtoken.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_oauth_tokens = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthtoken.ClientTable,
			Columns: []string{oauthtoken.ClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.oauth_client_tokens = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OAuthTokenCreateBulk is the builder for creating many OAuthToken entities in bulk.
type OAuthTokenCreateBulk struct {
	config
	err      error
	builders []*OAuthTokenCreate
}

// Save creates the OAuthToken entities in the database.
func (_c *OAuthTokenCreateBulk) Save(ctx context.Context) ([]*OAuthToken, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthToken, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthTokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthTokenCreateBulk) SaveX(ctx context.Context) []*OAuthToken {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthTokenCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthTokenCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
