// Code generated by ent, DO NOT EDIT.

package postgresql

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Team-Haruki/Haruki-Toolbox-Backend/utils/database/postgresql/oauth2clientwebhookendpoint"
)

// OAuth2ClientWebhookEndpoint is the model entity for the OAuth2ClientWebhookEndpoint schema.
type OAuth2ClientWebhookEndpoint struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID string `json:"client_id,omitempty"`
	// CallbackURL holds the value of the "callback_url" field.
	CallbackURL string `json:"callback_url,omitempty"`
	// Bearer holds the value of the "bearer" field.
	Bearer *string `json:"bearer,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuth2ClientWebhookEndpoint) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauth2clientwebhookendpoint.FieldEnabled:
			values[i] = new(sql.NullBool)
		case oauth2clientwebhookendpoint.FieldID, oauth2clientwebhookendpoint.FieldClientID, oauth2clientwebhookendpoint.FieldCallbackURL, oauth2clientwebhookendpoint.FieldBearer:
			values[i] = new(sql.NullString)
		case oauth2clientwebhookendpoint.FieldCreatedAt, oauth2clientwebhookendpoint.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuth2ClientWebhookEndpoint fields.
func (_m *OAuth2ClientWebhookEndpoint) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauth2clientwebhookendpoint.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case oauth2clientwebhookendpoint.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case oauth2clientwebhookendpoint.FieldCallbackURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field callback_url", values[i])
			} else if value.Valid {
				_m.CallbackURL = value.String
			}
		case oauth2clientwebhookendpoint.FieldBearer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bearer", values[i])
			} else if value.Valid {
				_m.Bearer = new(string)
				*_m.Bearer = value.String
			}
		case oauth2clientwebhookendpoint.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case oauth2clientwebhookendpoint.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauth2clientwebhookendpoint.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuth2ClientWebhookEndpoint.
// This includes values selected through modifiers, order, etc.
func (_m *OAuth2ClientWebhookEndpoint) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OAuth2ClientWebhookEndpoint.
// Note that you need to call OAuth2ClientWebhookEndpoint.Unwrap() before calling this method if this OAuth2ClientWebhookEndpoint
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuth2ClientWebhookEndpoint) Update() *OAuth2ClientWebhookEndpointUpdateOne {
	return NewOAuth2ClientWebhookEndpointClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuth2ClientWebhookEndpoint entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuth2ClientWebhookEndpoint) Unwrap() *OAuth2ClientWebhookEndpoint {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("postgresql: OAuth2ClientWebhookEndpoint is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuth2ClientWebhookEndpoint) String() string {
	var builder strings.Builder
	builder.WriteString("OAuth2ClientWebhookEndpoint(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("callback_url=")
	builder.WriteString(_m.CallbackURL)
	builder.WriteString(", ")
	if v := _m.Bearer; v != nil {
		builder.WriteString("bearer=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OAuth2ClientWebhookEndpoints is a parsable slice of OAuth2ClientWebhookEndpoint.
type OAuth2ClientWebhookEndpoints []*OAuth2ClientWebhookEndpoint
