// Code generated by ent, DO NOT EDIT.

package postgresql

import (
	"encoding/json"
	"fmt"
	"haruki-suite/utils/database/postgresql/riskevent"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RiskEvent is the model entity for the RiskEvent schema.
type RiskEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// EventTime holds the value of the "event_time" field.
	EventTime time.Time `json:"event_time,omitempty"`
	// Status holds the value of the "status" field.
	Status riskevent.Status `json:"status,omitempty"`
	// Severity holds the value of the "severity" field.
	Severity riskevent.Severity `json:"severity,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// ActorUserID holds the value of the "actor_user_id" field.
	ActorUserID *string `json:"actor_user_id,omitempty"`
	// TargetUserID holds the value of the "target_user_id" field.
	TargetUserID *string `json:"target_user_id,omitempty"`
	// IP holds the value of the "ip" field.
	IP *string `json:"ip,omitempty"`
	// Action holds the value of the "action" field.
	Action *string `json:"action,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// ResolvedAt holds the value of the "resolved_at" field.
	ResolvedAt *time.Time `json:"resolved_at,omitempty"`
	// ResolvedBy holds the value of the "resolved_by" field.
	ResolvedBy *string `json:"resolved_by,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata     map[string]interface{} `json:"metadata,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RiskEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case riskevent.FieldMetadata:
			values[i] = new([]byte)
		case riskevent.FieldID:
			values[i] = new(sql.NullInt64)
		case riskevent.FieldStatus, riskevent.FieldSeverity, riskevent.FieldSource, riskevent.FieldActorUserID, riskevent.FieldTargetUserID, riskevent.FieldIP, riskevent.FieldAction, riskevent.FieldReason, riskevent.FieldResolvedBy:
			values[i] = new(sql.NullString)
		case riskevent.FieldEventTime, riskevent.FieldResolvedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RiskEvent fields.
func (_m *RiskEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case riskevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case riskevent.FieldEventTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field event_time", values[i])
			} else if value.Valid {
				_m.EventTime = value.Time
			}
		case riskevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = riskevent.Status(value.String)
			}
		case riskevent.FieldSeverity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field severity", values[i])
			} else if value.Valid {
				_m.Severity = riskevent.Severity(value.String)
			}
		case riskevent.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case riskevent.FieldActorUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_user_id", values[i])
			} else if value.Valid {
				_m.ActorUserID = new(string)
				*_m.ActorUserID = value.String
			}
		case riskevent.FieldTargetUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_user_id", values[i])
			} else if value.Valid {
				_m.TargetUserID = new(string)
				*_m.TargetUserID = value.String
			}
		case riskevent.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = new(string)
				*_m.IP = value.String
			}
		case riskevent.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = new(string)
				*_m.Action = value.String
			}
		case riskevent.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case riskevent.FieldResolvedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_at", values[i])
			} else if value.Valid {
				_m.ResolvedAt = new(time.Time)
				*_m.ResolvedAt = value.Time
			}
		case riskevent.FieldResolvedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_by", values[i])
			} else if value.Valid {
				_m.ResolvedBy = new(string)
				*_m.ResolvedBy = value.String
			}
		case riskevent.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RiskEvent.
// This includes values selected through modifiers, order, etc.
func (_m *RiskEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RiskEvent.
// Note that you need to call RiskEvent.Unwrap() before calling this method if this RiskEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RiskEvent) Update() *RiskEventUpdateOne {
	return NewRiskEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RiskEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RiskEvent) Unwrap() *RiskEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("postgresql: RiskEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RiskEvent) String() string {
	var builder strings.Builder
	builder.WriteString("RiskEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_time=")
	builder.WriteString(_m.EventTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("severity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Severity))
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.ActorUserID; v != nil {
		builder.WriteString("actor_user_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TargetUserID; v != nil {
		builder.WriteString("target_user_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IP; v != nil {
		builder.WriteString("ip=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Action; v != nil {
		builder.WriteString("action=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResolvedAt; v != nil {
		builder.WriteString("resolved_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ResolvedBy; v != nil {
		builder.WriteString("resolved_by=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// RiskEvents is a parsable slice of RiskEvent.
type RiskEvents []*RiskEvent
