// Code generated by ent, DO NOT EDIT.

package postgresql

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Team-Haruki/Haruki-Toolbox-Backend/utils/database/postgresql/sponsorafdianorder"
)

// SponsorAfdianOrder is the model entity for the SponsorAfdianOrder schema.
type SponsorAfdianOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// SponsorID holds the value of the "sponsor_id" field.
	SponsorID string `json:"sponsor_id,omitempty"`
	// AfdianUserID holds the value of the "afdian_user_id" field.
	AfdianUserID string `json:"afdian_user_id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID string `json:"plan_id,omitempty"`
	// PlanTitle holds the value of the "plan_title" field.
	PlanTitle string `json:"plan_title,omitempty"`
	// ProductType holds the value of the "product_type" field.
	ProductType int `json:"product_type,omitzero"`
	// Month holds the value of the "month" field.
	Month int `json:"month,omitzero"`
	// Status holds the value of the "status" field.
	Status int `json:"status,omitzero"`
	// TotalAmount holds the value of the "total_amount" field.
	TotalAmount string `json:"total_amount,omitempty"`
	// ShowAmount holds the value of the "show_amount" field.
	ShowAmount string `json:"show_amount,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark string `json:"remark,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt time.Time `json:"paid_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SponsorAfdianOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sponsorafdianorder.FieldProductType, sponsorafdianorder.FieldMonth, sponsorafdianorder.FieldStatus:
			values[i] = new(sql.NullInt64)
		case sponsorafdianorder.FieldID, sponsorafdianorder.FieldSponsorID, sponsorafdianorder.FieldAfdianUserID, sponsorafdianorder.FieldPlanID, sponsorafdianorder.FieldPlanTitle, sponsorafdianorder.FieldTotalAmount, sponsorafdianorder.FieldShowAmount, sponsorafdianorder.FieldRemark:
			values[i] = new(sql.NullString)
		case sponsorafdianorder.FieldPaidAt, sponsorafdianorder.FieldCreatedAt, sponsorafdianorder.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SponsorAfdianOrder fields.
func (_m *SponsorAfdianOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sponsorafdianorder.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case sponsorafdianorder.FieldSponsorID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sponsor_id", values[i])
			} else if value.Valid {
				_m.SponsorID = value.String
			}
		case sponsorafdianorder.FieldAfdianUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field afdian_user_id", values[i])
			} else if value.Valid {
				_m.AfdianUserID = value.String
			}
		case sponsorafdianorder.FieldPlanID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = value.String
			}
		case sponsorafdianorder.FieldPlanTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan_title", values[i])
			} else if value.Valid {
				_m.PlanTitle = value.String
			}
		case sponsorafdianorder.FieldProductType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field product_type", values[i])
			} else if value.Valid {
				_m.ProductType = int(value.Int64)
			}
		case sponsorafdianorder.FieldMonth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field month", values[i])
			} else if value.Valid {
				_m.Month = int(value.Int64)
			}
		case sponsorafdianorder.FieldStatus:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = int(value.Int64)
			}
		case sponsorafdianorder.FieldTotalAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field total_amount", values[i])
			} else if value.Valid {
				_m.TotalAmount = value.String
			}
		case sponsorafdianorder.FieldShowAmount:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field show_amount", values[i])
			} else if value.Valid {
				_m.ShowAmount = value.String
			}
		case sponsorafdianorder.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		case sponsorafdianorder.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = value.Time
			}
		case sponsorafdianorder.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sponsorafdianorder.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SponsorAfdianOrder.
// This includes values selected through modifiers, order, etc.
func (_m *SponsorAfdianOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SponsorAfdianOrder.
// Note that you need to call SponsorAfdianOrder.Unwrap() before calling this method if this SponsorAfdianOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SponsorAfdianOrder) Update() *SponsorAfdianOrderUpdateOne {
	return NewSponsorAfdianOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SponsorAfdianOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SponsorAfdianOrder) Unwrap() *SponsorAfdianOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("postgresql: SponsorAfdianOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SponsorAfdianOrder) String() string {
	var builder strings.Builder
	builder.WriteString("SponsorAfdianOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("sponsor_id=")
	builder.WriteString(_m.SponsorID)
	builder.WriteString(", ")
	builder.WriteString("afdian_user_id=")
	builder.WriteString(_m.AfdianUserID)
	builder.WriteString(", ")
	builder.WriteString("plan_id=")
	builder.WriteString(_m.PlanID)
	builder.WriteString(", ")
	builder.WriteString("plan_title=")
	builder.WriteString(_m.PlanTitle)
	builder.WriteString(", ")
	builder.WriteString("product_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductType))
	builder.WriteString(", ")
	builder.WriteString("month=")
	builder.WriteString(fmt.Sprintf("%v", _m.Month))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("total_amount=")
	builder.WriteString(_m.TotalAmount)
	builder.WriteString(", ")
	builder.WriteString("show_amount=")
	builder.WriteString(_m.ShowAmount)
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteString(", ")
	builder.WriteString("paid_at=")
	builder.WriteString(_m.PaidAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SponsorAfdianOrders is a parsable slice of SponsorAfdianOrder.
type SponsorAfdianOrders []*SponsorAfdianOrder
