// Code generated by ent, DO NOT EDIT.

package postgresql

import (
	"fmt"
	"haruki-suite/utils/database/postgresql/ticket"
	"haruki-suite/utils/database/postgresql/ticketmessage"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TicketMessage is the model entity for the TicketMessage schema.
type TicketMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// TicketID holds the value of the "ticket_id" field.
	TicketID int `json:"ticket_id,omitempty"`
	// SenderUserID holds the value of the "sender_user_id" field.
	SenderUserID *string `json:"sender_user_id,omitempty"`
	// SenderRole holds the value of the "sender_role" field.
	SenderRole ticketmessage.SenderRole `json:"sender_role,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// Internal holds the value of the "internal" field.
	Internal bool `json:"internal,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TicketMessageQuery when eager-loading is set.
	Edges        TicketMessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TicketMessageEdges holds the relations/edges for other nodes in the graph.
type TicketMessageEdges struct {
	// Ticket holds the value of the ticket edge.
	Ticket *Ticket `json:"ticket,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TicketOrErr returns the Ticket value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TicketMessageEdges) TicketOrErr() (*Ticket, error) {
	if e.Ticket != nil {
		return e.Ticket, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: ticket.Label}
	}
	return nil, &NotLoadedError{edge: "ticket"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TicketMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ticketmessage.FieldInternal:
			values[i] = new(sql.NullBool)
		case ticketmessage.FieldID, ticketmessage.FieldTicketID:
			values[i] = new(sql.NullInt64)
		case ticketmessage.FieldSenderUserID, ticketmessage.FieldSenderRole, ticketmessage.FieldMessage:
			values[i] = new(sql.NullString)
		case ticketmessage.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TicketMessage fields.
func (_m *TicketMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ticketmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ticketmessage.FieldTicketID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ticket_id", values[i])
			} else if value.Valid {
				_m.TicketID = int(value.Int64)
			}
		case ticketmessage.FieldSenderUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_user_id", values[i])
			} else if value.Valid {
				_m.SenderUserID = new(string)
				*_m.SenderUserID = value.String
			}
		case ticketmessage.FieldSenderRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sender_role", values[i])
			} else if value.Valid {
				_m.SenderRole = ticketmessage.SenderRole(value.String)
			}
		case ticketmessage.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case ticketmessage.FieldInternal:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field internal", values[i])
			} else if value.Valid {
				_m.Internal = value.Bool
			}
		case ticketmessage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TicketMessage.
// This includes values selected through modifiers, order, etc.
func (_m *TicketMessage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryTicket queries the "ticket" edge of the TicketMessage entity.
func (_m *TicketMessage) QueryTicket() *TicketQuery {
	return NewTicketMessageClient(_m.config).QueryTicket(_m)
}

// Update returns a builder for updating this TicketMessage.
// Note that you need to call TicketMessage.Unwrap() before calling this method if this TicketMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TicketMessage) Update() *TicketMessageUpdateOne {
	return NewTicketMessageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TicketMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TicketMessage) Unwrap() *TicketMessage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("postgresql: TicketMessage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TicketMessage) String() string {
	var builder strings.Builder
	builder.WriteString("TicketMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("ticket_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TicketID))
	builder.WriteString(", ")
	if v := _m.SenderUserID; v != nil {
		builder.WriteString("sender_user_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("sender_role=")
	builder.WriteString(fmt.Sprintf("%v", _m.SenderRole))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("internal=")
	builder.WriteString(fmt.Sprintf("%v", _m.Internal))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TicketMessages is a parsable slice of TicketMessage.
type TicketMessages []*TicketMessage
