// Code generated by ent, DO NOT EDIT.

package postgresql

import (
	"fmt"
	"haruki-suite/utils/database/postgresql/uploadlog"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UploadLog is the model entity for the UploadLog schema.
type UploadLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// jp en tw kr cn
	Server string `json:"server,omitempty"`
	// GameUserID holds the value of the "game_user_id" field.
	GameUserID string `json:"game_user_id,omitempty"`
	// ToolboxUserID holds the value of the "toolbox_user_id" field.
	ToolboxUserID string `json:"toolbox_user_id,omitempty"`
	// suite mysekai mysekai_birthday
	DataType string `json:"data_type,omitempty"`
	// manual harukiproxy iosproxy inherit
	UploadMethod string `json:"upload_method,omitempty"`
	// Success holds the value of the "success" field.
	Success      bool `json:"success,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UploadLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case uploadlog.FieldSuccess:
			values[i] = new(sql.NullBool)
		case uploadlog.FieldID:
			values[i] = new(sql.NullInt64)
		case uploadlog.FieldServer, uploadlog.FieldGameUserID, uploadlog.FieldToolboxUserID, uploadlog.FieldDataType, uploadlog.FieldUploadMethod:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UploadLog fields.
func (_m *UploadLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case uploadlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case uploadlog.FieldServer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field server", values[i])
			} else if value.Valid {
				_m.Server = value.String
			}
		case uploadlog.FieldGameUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field game_user_id", values[i])
			} else if value.Valid {
				_m.GameUserID = value.String
			}
		case uploadlog.FieldToolboxUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field toolbox_user_id", values[i])
			} else if value.Valid {
				_m.ToolboxUserID = value.String
			}
		case uploadlog.FieldDataType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data_type", values[i])
			} else if value.Valid {
				_m.DataType = value.String
			}
		case uploadlog.FieldUploadMethod:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upload_method", values[i])
			} else if value.Valid {
				_m.UploadMethod = value.String
			}
		case uploadlog.FieldSuccess:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field success", values[i])
			} else if value.Valid {
				_m.Success = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UploadLog.
// This includes values selected through modifiers, order, etc.
func (_m *UploadLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UploadLog.
// Note that you need to call UploadLog.Unwrap() before calling this method if this UploadLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UploadLog) Update() *UploadLogUpdateOne {
	return NewUploadLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UploadLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UploadLog) Unwrap() *UploadLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("postgresql: UploadLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UploadLog) String() string {
	var builder strings.Builder
	builder.WriteString("UploadLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("server=")
	builder.WriteString(_m.Server)
	builder.WriteString(", ")
	builder.WriteString("game_user_id=")
	builder.WriteString(_m.GameUserID)
	builder.WriteString(", ")
	builder.WriteString("toolbox_user_id=")
	builder.WriteString(_m.ToolboxUserID)
	builder.WriteString(", ")
	builder.WriteString("data_type=")
	builder.WriteString(_m.DataType)
	builder.WriteString(", ")
	builder.WriteString("upload_method=")
	builder.WriteString(_m.UploadMethod)
	builder.WriteString(", ")
	builder.WriteString("success=")
	builder.WriteString(fmt.Sprintf("%v", _m.Success))
	builder.WriteByte(')')
	return builder.String()
}

// UploadLogs is a parsable slice of UploadLog.
type UploadLogs []*UploadLog
