// Code generated by ent, DO NOT EDIT.

package postgresql

import (
	"context"
	"errors"
	"fmt"
	"haruki-suite/utils/database/postgresql/webhookendpoint"
	"haruki-suite/utils/database/postgresql/webhooksubscription"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebhookSubscriptionCreate is the builder for creating a WebhookSubscription entity.
type WebhookSubscriptionCreate struct {
	config
	mutation *WebhookSubscriptionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *WebhookSubscriptionCreate) SetUserID(v string) *WebhookSubscriptionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetServer sets the "server" field.
func (_c *WebhookSubscriptionCreate) SetServer(v string) *WebhookSubscriptionCreate {
	_c.mutation.SetServer(v)
	return _c
}

// SetDataType sets the "data_type" field.
func (_c *WebhookSubscriptionCreate) SetDataType(v string) *WebhookSubscriptionCreate {
	_c.mutation.SetDataType(v)
	return _c
}

// SetWebhookID sets the "webhook_id" field.
func (_c *WebhookSubscriptionCreate) SetWebhookID(v string) *WebhookSubscriptionCreate {
	_c.mutation.SetWebhookID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *WebhookSubscriptionCreate) SetCreatedAt(v time.Time) *WebhookSubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *WebhookSubscriptionCreate) SetNillableCreatedAt(v *time.Time) *WebhookSubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetEndpointID sets the "endpoint" edge to the WebhookEndpoint entity by ID.
func (_c *WebhookSubscriptionCreate) SetEndpointID(id string) *WebhookSubscriptionCreate {
	_c.mutation.SetEndpointID(id)
	return _c
}

// SetEndpoint sets the "endpoint" edge to the WebhookEndpoint entity.
func (_c *WebhookSubscriptionCreate) SetEndpoint(v *WebhookEndpoint) *WebhookSubscriptionCreate {
	return _c.SetEndpointID(v.ID)
}

// Mutation returns the WebhookSubscriptionMutation object of the builder.
func (_c *WebhookSubscriptionCreate) Mutation() *WebhookSubscriptionMutation {
	return _c.mutation
}

// Save creates the WebhookSubscription in the database.
func (_c *WebhookSubscriptionCreate) Save(ctx context.Context) (*WebhookSubscription, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WebhookSubscriptionCreate) SaveX(ctx context.Context) *WebhookSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookSubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookSubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WebhookSubscriptionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := webhooksubscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WebhookSubscriptionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`postgresql: missing required field "WebhookSubscription.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := webhooksubscription.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`postgresql: validator failed for field "WebhookSubscription.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Server(); !ok {
		return &ValidationError{Name: "server", err: errors.New(`postgresql: missing required field "WebhookSubscription.server"`)}
	}
	if v, ok := _c.mutation.Server(); ok {
		if err := webhooksubscription.ServerValidator(v); err != nil {
			return &ValidationError{Name: "server", err: fmt.Errorf(`postgresql: validator failed for field "WebhookSubscription.server": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DataType(); !ok {
		return &ValidationError{Name: "data_type", err: errors.New(`postgresql: missing required field "WebhookSubscription.data_type"`)}
	}
	if v, ok := _c.mutation.DataType(); ok {
		if err := webhooksubscription.DataTypeValidator(v); err != nil {
			return &ValidationError{Name: "data_type", err: fmt.Errorf(`postgresql: validator failed for field "WebhookSubscription.data_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.WebhookID(); !ok {
		return &ValidationError{Name: "webhook_id", err: errors.New(`postgresql: missing required field "WebhookSubscription.webhook_id"`)}
	}
	if v, ok := _c.mutation.WebhookID(); ok {
		if err := webhooksubscription.WebhookIDValidator(v); err != nil {
			return &ValidationError{Name: "webhook_id", err: fmt.Errorf(`postgresql: validator failed for field "WebhookSubscription.webhook_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`postgresql: missing required field "WebhookSubscription.created_at"`)}
	}
	if len(_c.mutation.EndpointIDs()) == 0 {
		return &ValidationError{Name: "endpoint", err: errors.New(`postgresql: missing required edge "WebhookSubscription.endpoint"`)}
	}
	return nil
}

func (_c *WebhookSubscriptionCreate) sqlSave(ctx context.Context) (*WebhookSubscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WebhookSubscriptionCreate) createSpec() (*WebhookSubscription, *sqlgraph.CreateSpec) {
	var (
		_node = &WebhookSubscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(webhooksubscription.Table, sqlgraph.NewFieldSpec(webhooksubscription.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(webhooksubscription.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Server(); ok {
		_spec.SetField(webhooksubscription.FieldServer, field.TypeString, value)
		_node.Server = value
	}
	if value, ok := _c.mutation.DataType(); ok {
		_spec.SetField(webhooksubscription.FieldDataType, field.TypeString, value)
		_node.DataType = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(webhooksubscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.EndpointIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   webhooksubscription.EndpointTable,
			Columns: []string{webhooksubscription.EndpointColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(webhookendpoint.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WebhookID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WebhookSubscriptionCreateBulk is the builder for creating many WebhookSubscription entities in bulk.
type WebhookSubscriptionCreateBulk struct {
	config
	err      error
	builders []*WebhookSubscriptionCreate
}

// Save creates the WebhookSubscription entities in the database.
func (_c *WebhookSubscriptionCreateBulk) Save(ctx context.Context) ([]*WebhookSubscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*WebhookSubscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WebhookSubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WebhookSubscriptionCreateBulk) SaveX(ctx context.Context) []*WebhookSubscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WebhookSubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WebhookSubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
