// Code generated by ent, DO NOT EDIT.

package user

import (
	"haruki-suite/utils/database/postgresql/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.User {
	return predicate.User(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.User {
	return predicate.User(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// AvatarPath applies equality check predicate on the "avatar_path" field. It's identical to AvatarPathEQ.
func AvatarPath(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarPath, v))
}

// AllowCnMysekai applies equality check predicate on the "allow_cn_mysekai" field. It's identical to AllowCnMysekaiEQ.
func AllowCnMysekai(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAllowCnMysekai, v))
}

// Banned applies equality check predicate on the "banned" field. It's identical to BannedEQ.
func Banned(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBanned, v))
}

// BanReason applies equality check predicate on the "ban_reason" field. It's identical to BanReasonEQ.
func BanReason(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBanReason, v))
}

// KratosIdentityID applies equality check predicate on the "kratos_identity_id" field. It's identical to KratosIdentityIDEQ.
func KratosIdentityID(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldKratosIdentityID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldName, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldEmail, v))
}

// AvatarPathEQ applies the EQ predicate on the "avatar_path" field.
func AvatarPathEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAvatarPath, v))
}

// AvatarPathNEQ applies the NEQ predicate on the "avatar_path" field.
func AvatarPathNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAvatarPath, v))
}

// AvatarPathIn applies the In predicate on the "avatar_path" field.
func AvatarPathIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldAvatarPath, vs...))
}

// AvatarPathNotIn applies the NotIn predicate on the "avatar_path" field.
func AvatarPathNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldAvatarPath, vs...))
}

// AvatarPathGT applies the GT predicate on the "avatar_path" field.
func AvatarPathGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldAvatarPath, v))
}

// AvatarPathGTE applies the GTE predicate on the "avatar_path" field.
func AvatarPathGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldAvatarPath, v))
}

// AvatarPathLT applies the LT predicate on the "avatar_path" field.
func AvatarPathLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldAvatarPath, v))
}

// AvatarPathLTE applies the LTE predicate on the "avatar_path" field.
func AvatarPathLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldAvatarPath, v))
}

// AvatarPathContains applies the Contains predicate on the "avatar_path" field.
func AvatarPathContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldAvatarPath, v))
}

// AvatarPathHasPrefix applies the HasPrefix predicate on the "avatar_path" field.
func AvatarPathHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldAvatarPath, v))
}

// AvatarPathHasSuffix applies the HasSuffix predicate on the "avatar_path" field.
func AvatarPathHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldAvatarPath, v))
}

// AvatarPathIsNil applies the IsNil predicate on the "avatar_path" field.
func AvatarPathIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldAvatarPath))
}

// AvatarPathNotNil applies the NotNil predicate on the "avatar_path" field.
func AvatarPathNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldAvatarPath))
}

// AvatarPathEqualFold applies the EqualFold predicate on the "avatar_path" field.
func AvatarPathEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldAvatarPath, v))
}

// AvatarPathContainsFold applies the ContainsFold predicate on the "avatar_path" field.
func AvatarPathContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldAvatarPath, v))
}

// AllowCnMysekaiEQ applies the EQ predicate on the "allow_cn_mysekai" field.
func AllowCnMysekaiEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldAllowCnMysekai, v))
}

// AllowCnMysekaiNEQ applies the NEQ predicate on the "allow_cn_mysekai" field.
func AllowCnMysekaiNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldAllowCnMysekai, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v Role) predicate.User {
	return predicate.User(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v Role) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...Role) predicate.User {
	return predicate.User(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...Role) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldRole, vs...))
}

// BannedEQ applies the EQ predicate on the "banned" field.
func BannedEQ(v bool) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBanned, v))
}

// BannedNEQ applies the NEQ predicate on the "banned" field.
func BannedNEQ(v bool) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldBanned, v))
}

// BanReasonEQ applies the EQ predicate on the "ban_reason" field.
func BanReasonEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldBanReason, v))
}

// BanReasonNEQ applies the NEQ predicate on the "ban_reason" field.
func BanReasonNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldBanReason, v))
}

// BanReasonIn applies the In predicate on the "ban_reason" field.
func BanReasonIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldBanReason, vs...))
}

// BanReasonNotIn applies the NotIn predicate on the "ban_reason" field.
func BanReasonNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldBanReason, vs...))
}

// BanReasonGT applies the GT predicate on the "ban_reason" field.
func BanReasonGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldBanReason, v))
}

// BanReasonGTE applies the GTE predicate on the "ban_reason" field.
func BanReasonGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldBanReason, v))
}

// BanReasonLT applies the LT predicate on the "ban_reason" field.
func BanReasonLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldBanReason, v))
}

// BanReasonLTE applies the LTE predicate on the "ban_reason" field.
func BanReasonLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldBanReason, v))
}

// BanReasonContains applies the Contains predicate on the "ban_reason" field.
func BanReasonContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldBanReason, v))
}

// BanReasonHasPrefix applies the HasPrefix predicate on the "ban_reason" field.
func BanReasonHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldBanReason, v))
}

// BanReasonHasSuffix applies the HasSuffix predicate on the "ban_reason" field.
func BanReasonHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldBanReason, v))
}

// BanReasonIsNil applies the IsNil predicate on the "ban_reason" field.
func BanReasonIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldBanReason))
}

// BanReasonNotNil applies the NotNil predicate on the "ban_reason" field.
func BanReasonNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldBanReason))
}

// BanReasonEqualFold applies the EqualFold predicate on the "ban_reason" field.
func BanReasonEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldBanReason, v))
}

// BanReasonContainsFold applies the ContainsFold predicate on the "ban_reason" field.
func BanReasonContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldBanReason, v))
}

// KratosIdentityIDEQ applies the EQ predicate on the "kratos_identity_id" field.
func KratosIdentityIDEQ(v string) predicate.User {
	return predicate.User(sql.FieldEQ(FieldKratosIdentityID, v))
}

// KratosIdentityIDNEQ applies the NEQ predicate on the "kratos_identity_id" field.
func KratosIdentityIDNEQ(v string) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldKratosIdentityID, v))
}

// KratosIdentityIDIn applies the In predicate on the "kratos_identity_id" field.
func KratosIdentityIDIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldIn(FieldKratosIdentityID, vs...))
}

// KratosIdentityIDNotIn applies the NotIn predicate on the "kratos_identity_id" field.
func KratosIdentityIDNotIn(vs ...string) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldKratosIdentityID, vs...))
}

// KratosIdentityIDGT applies the GT predicate on the "kratos_identity_id" field.
func KratosIdentityIDGT(v string) predicate.User {
	return predicate.User(sql.FieldGT(FieldKratosIdentityID, v))
}

// KratosIdentityIDGTE applies the GTE predicate on the "kratos_identity_id" field.
func KratosIdentityIDGTE(v string) predicate.User {
	return predicate.User(sql.FieldGTE(FieldKratosIdentityID, v))
}

// KratosIdentityIDLT applies the LT predicate on the "kratos_identity_id" field.
func KratosIdentityIDLT(v string) predicate.User {
	return predicate.User(sql.FieldLT(FieldKratosIdentityID, v))
}

// KratosIdentityIDLTE applies the LTE predicate on the "kratos_identity_id" field.
func KratosIdentityIDLTE(v string) predicate.User {
	return predicate.User(sql.FieldLTE(FieldKratosIdentityID, v))
}

// KratosIdentityIDContains applies the Contains predicate on the "kratos_identity_id" field.
func KratosIdentityIDContains(v string) predicate.User {
	return predicate.User(sql.FieldContains(FieldKratosIdentityID, v))
}

// KratosIdentityIDHasPrefix applies the HasPrefix predicate on the "kratos_identity_id" field.
func KratosIdentityIDHasPrefix(v string) predicate.User {
	return predicate.User(sql.FieldHasPrefix(FieldKratosIdentityID, v))
}

// KratosIdentityIDHasSuffix applies the HasSuffix predicate on the "kratos_identity_id" field.
func KratosIdentityIDHasSuffix(v string) predicate.User {
	return predicate.User(sql.FieldHasSuffix(FieldKratosIdentityID, v))
}

// KratosIdentityIDIsNil applies the IsNil predicate on the "kratos_identity_id" field.
func KratosIdentityIDIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldKratosIdentityID))
}

// KratosIdentityIDNotNil applies the NotNil predicate on the "kratos_identity_id" field.
func KratosIdentityIDNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldKratosIdentityID))
}

// KratosIdentityIDEqualFold applies the EqualFold predicate on the "kratos_identity_id" field.
func KratosIdentityIDEqualFold(v string) predicate.User {
	return predicate.User(sql.FieldEqualFold(FieldKratosIdentityID, v))
}

// KratosIdentityIDContainsFold applies the ContainsFold predicate on the "kratos_identity_id" field.
func KratosIdentityIDContainsFold(v string) predicate.User {
	return predicate.User(sql.FieldContainsFold(FieldKratosIdentityID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.User {
	return predicate.User(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.User {
	return predicate.User(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.User {
	return predicate.User(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.User {
	return predicate.User(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.User {
	return predicate.User(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.User {
	return predicate.User(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.User {
	return predicate.User(sql.FieldNotNull(FieldCreatedAt))
}

// HasSocialPlatformInfo applies the HasEdge predicate on the "social_platform_info" edge.
func HasSocialPlatformInfo() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, SocialPlatformInfoTable, SocialPlatformInfoColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSocialPlatformInfoWith applies the HasEdge predicate on the "social_platform_info" edge with a given conditions (other predicates).
func HasSocialPlatformInfoWith(preds ...predicate.SocialPlatformInfo) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newSocialPlatformInfoStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAuthorizedSocialPlatforms applies the HasEdge predicate on the "authorized_social_platforms" edge.
func HasAuthorizedSocialPlatforms() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AuthorizedSocialPlatformsTable, AuthorizedSocialPlatformsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorizedSocialPlatformsWith applies the HasEdge predicate on the "authorized_social_platforms" edge with a given conditions (other predicates).
func HasAuthorizedSocialPlatformsWith(preds ...predicate.AuthorizeSocialPlatformInfo) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newAuthorizedSocialPlatformsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGameAccountBindings applies the HasEdge predicate on the "game_account_bindings" edge.
func HasGameAccountBindings() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, GameAccountBindingsTable, GameAccountBindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGameAccountBindingsWith applies the HasEdge predicate on the "game_account_bindings" edge with a given conditions (other predicates).
func HasGameAccountBindingsWith(preds ...predicate.GameAccountBinding) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newGameAccountBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIosScriptCode applies the HasEdge predicate on the "ios_script_code" edge.
func HasIosScriptCode() predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, IosScriptCodeTable, IosScriptCodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIosScriptCodeWith applies the HasEdge predicate on the "ios_script_code" edge with a given conditions (other predicates).
func HasIosScriptCodeWith(preds ...predicate.IOSScriptCode) predicate.User {
	return predicate.User(func(s *sql.Selector) {
		step := newIosScriptCodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.User) predicate.User {
	return predicate.User(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.User) predicate.User {
	return predicate.User(sql.NotPredicates(p))
}
