// Code generated by ent, DO NOT EDIT.

package gameaccountdatagrant

import (
	"haruki-suite/utils/database/postgresql/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLTE(FieldID, id))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldOwnerUserID, v))
}

// GranteeUserID applies equality check predicate on the "grantee_user_id" field. It's identical to GranteeUserIDEQ.
func GranteeUserID(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldGranteeUserID, v))
}

// Server applies equality check predicate on the "server" field. It's identical to ServerEQ.
func Server(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldServer, v))
}

// GameUserID applies equality check predicate on the "game_user_id" field. It's identical to GameUserIDEQ.
func GameUserID(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldGameUserID, v))
}

// DataType applies equality check predicate on the "data_type" field. It's identical to DataTypeEQ.
func DataType(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldDataType, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDGT applies the GT predicate on the "owner_user_id" field.
func OwnerUserIDGT(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGT(FieldOwnerUserID, v))
}

// OwnerUserIDGTE applies the GTE predicate on the "owner_user_id" field.
func OwnerUserIDGTE(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGTE(FieldOwnerUserID, v))
}

// OwnerUserIDLT applies the LT predicate on the "owner_user_id" field.
func OwnerUserIDLT(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLT(FieldOwnerUserID, v))
}

// OwnerUserIDLTE applies the LTE predicate on the "owner_user_id" field.
func OwnerUserIDLTE(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLTE(FieldOwnerUserID, v))
}

// OwnerUserIDContains applies the Contains predicate on the "owner_user_id" field.
func OwnerUserIDContains(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldContains(FieldOwnerUserID, v))
}

// OwnerUserIDHasPrefix applies the HasPrefix predicate on the "owner_user_id" field.
func OwnerUserIDHasPrefix(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldHasPrefix(FieldOwnerUserID, v))
}

// OwnerUserIDHasSuffix applies the HasSuffix predicate on the "owner_user_id" field.
func OwnerUserIDHasSuffix(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldHasSuffix(FieldOwnerUserID, v))
}

// OwnerUserIDEqualFold applies the EqualFold predicate on the "owner_user_id" field.
func OwnerUserIDEqualFold(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEqualFold(FieldOwnerUserID, v))
}

// OwnerUserIDContainsFold applies the ContainsFold predicate on the "owner_user_id" field.
func OwnerUserIDContainsFold(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldContainsFold(FieldOwnerUserID, v))
}

// GranteeUserIDEQ applies the EQ predicate on the "grantee_user_id" field.
func GranteeUserIDEQ(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldGranteeUserID, v))
}

// GranteeUserIDNEQ applies the NEQ predicate on the "grantee_user_id" field.
func GranteeUserIDNEQ(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNEQ(FieldGranteeUserID, v))
}

// GranteeUserIDIn applies the In predicate on the "grantee_user_id" field.
func GranteeUserIDIn(vs ...string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldIn(FieldGranteeUserID, vs...))
}

// GranteeUserIDNotIn applies the NotIn predicate on the "grantee_user_id" field.
func GranteeUserIDNotIn(vs ...string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNotIn(FieldGranteeUserID, vs...))
}

// GranteeUserIDGT applies the GT predicate on the "grantee_user_id" field.
func GranteeUserIDGT(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGT(FieldGranteeUserID, v))
}

// GranteeUserIDGTE applies the GTE predicate on the "grantee_user_id" field.
func GranteeUserIDGTE(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGTE(FieldGranteeUserID, v))
}

// GranteeUserIDLT applies the LT predicate on the "grantee_user_id" field.
func GranteeUserIDLT(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLT(FieldGranteeUserID, v))
}

// GranteeUserIDLTE applies the LTE predicate on the "grantee_user_id" field.
func GranteeUserIDLTE(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLTE(FieldGranteeUserID, v))
}

// GranteeUserIDContains applies the Contains predicate on the "grantee_user_id" field.
func GranteeUserIDContains(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldContains(FieldGranteeUserID, v))
}

// GranteeUserIDHasPrefix applies the HasPrefix predicate on the "grantee_user_id" field.
func GranteeUserIDHasPrefix(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldHasPrefix(FieldGranteeUserID, v))
}

// GranteeUserIDHasSuffix applies the HasSuffix predicate on the "grantee_user_id" field.
func GranteeUserIDHasSuffix(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldHasSuffix(FieldGranteeUserID, v))
}

// GranteeUserIDEqualFold applies the EqualFold predicate on the "grantee_user_id" field.
func GranteeUserIDEqualFold(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEqualFold(FieldGranteeUserID, v))
}

// GranteeUserIDContainsFold applies the ContainsFold predicate on the "grantee_user_id" field.
func GranteeUserIDContainsFold(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldContainsFold(FieldGranteeUserID, v))
}

// ServerEQ applies the EQ predicate on the "server" field.
func ServerEQ(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldServer, v))
}

// ServerNEQ applies the NEQ predicate on the "server" field.
func ServerNEQ(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNEQ(FieldServer, v))
}

// ServerIn applies the In predicate on the "server" field.
func ServerIn(vs ...string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldIn(FieldServer, vs...))
}

// ServerNotIn applies the NotIn predicate on the "server" field.
func ServerNotIn(vs ...string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNotIn(FieldServer, vs...))
}

// ServerGT applies the GT predicate on the "server" field.
func ServerGT(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGT(FieldServer, v))
}

// ServerGTE applies the GTE predicate on the "server" field.
func ServerGTE(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGTE(FieldServer, v))
}

// ServerLT applies the LT predicate on the "server" field.
func ServerLT(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLT(FieldServer, v))
}

// ServerLTE applies the LTE predicate on the "server" field.
func ServerLTE(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLTE(FieldServer, v))
}

// ServerContains applies the Contains predicate on the "server" field.
func ServerContains(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldContains(FieldServer, v))
}

// ServerHasPrefix applies the HasPrefix predicate on the "server" field.
func ServerHasPrefix(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldHasPrefix(FieldServer, v))
}

// ServerHasSuffix applies the HasSuffix predicate on the "server" field.
func ServerHasSuffix(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldHasSuffix(FieldServer, v))
}

// ServerEqualFold applies the EqualFold predicate on the "server" field.
func ServerEqualFold(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEqualFold(FieldServer, v))
}

// ServerContainsFold applies the ContainsFold predicate on the "server" field.
func ServerContainsFold(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldContainsFold(FieldServer, v))
}

// GameUserIDEQ applies the EQ predicate on the "game_user_id" field.
func GameUserIDEQ(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldGameUserID, v))
}

// GameUserIDNEQ applies the NEQ predicate on the "game_user_id" field.
func GameUserIDNEQ(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNEQ(FieldGameUserID, v))
}

// GameUserIDIn applies the In predicate on the "game_user_id" field.
func GameUserIDIn(vs ...string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldIn(FieldGameUserID, vs...))
}

// GameUserIDNotIn applies the NotIn predicate on the "game_user_id" field.
func GameUserIDNotIn(vs ...string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNotIn(FieldGameUserID, vs...))
}

// GameUserIDGT applies the GT predicate on the "game_user_id" field.
func GameUserIDGT(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGT(FieldGameUserID, v))
}

// GameUserIDGTE applies the GTE predicate on the "game_user_id" field.
func GameUserIDGTE(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGTE(FieldGameUserID, v))
}

// GameUserIDLT applies the LT predicate on the "game_user_id" field.
func GameUserIDLT(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLT(FieldGameUserID, v))
}

// GameUserIDLTE applies the LTE predicate on the "game_user_id" field.
func GameUserIDLTE(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLTE(FieldGameUserID, v))
}

// GameUserIDContains applies the Contains predicate on the "game_user_id" field.
func GameUserIDContains(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldContains(FieldGameUserID, v))
}

// GameUserIDHasPrefix applies the HasPrefix predicate on the "game_user_id" field.
func GameUserIDHasPrefix(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldHasPrefix(FieldGameUserID, v))
}

// GameUserIDHasSuffix applies the HasSuffix predicate on the "game_user_id" field.
func GameUserIDHasSuffix(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldHasSuffix(FieldGameUserID, v))
}

// GameUserIDEqualFold applies the EqualFold predicate on the "game_user_id" field.
func GameUserIDEqualFold(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEqualFold(FieldGameUserID, v))
}

// GameUserIDContainsFold applies the ContainsFold predicate on the "game_user_id" field.
func GameUserIDContainsFold(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldContainsFold(FieldGameUserID, v))
}

// DataTypeEQ applies the EQ predicate on the "data_type" field.
func DataTypeEQ(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldDataType, v))
}

// DataTypeNEQ applies the NEQ predicate on the "data_type" field.
func DataTypeNEQ(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNEQ(FieldDataType, v))
}

// DataTypeIn applies the In predicate on the "data_type" field.
func DataTypeIn(vs ...string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldIn(FieldDataType, vs...))
}

// DataTypeNotIn applies the NotIn predicate on the "data_type" field.
func DataTypeNotIn(vs ...string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNotIn(FieldDataType, vs...))
}

// DataTypeGT applies the GT predicate on the "data_type" field.
func DataTypeGT(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGT(FieldDataType, v))
}

// DataTypeGTE applies the GTE predicate on the "data_type" field.
func DataTypeGTE(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGTE(FieldDataType, v))
}

// DataTypeLT applies the LT predicate on the "data_type" field.
func DataTypeLT(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLT(FieldDataType, v))
}

// DataTypeLTE applies the LTE predicate on the "data_type" field.
func DataTypeLTE(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLTE(FieldDataType, v))
}

// DataTypeContains applies the Contains predicate on the "data_type" field.
func DataTypeContains(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldContains(FieldDataType, v))
}

// DataTypeHasPrefix applies the HasPrefix predicate on the "data_type" field.
func DataTypeHasPrefix(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldHasPrefix(FieldDataType, v))
}

// DataTypeHasSuffix applies the HasSuffix predicate on the "data_type" field.
func DataTypeHasSuffix(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldHasSuffix(FieldDataType, v))
}

// DataTypeEqualFold applies the EqualFold predicate on the "data_type" field.
func DataTypeEqualFold(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEqualFold(FieldDataType, v))
}

// DataTypeContainsFold applies the ContainsFold predicate on the "data_type" field.
func DataTypeContainsFold(v string) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldContainsFold(FieldDataType, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasGrantee applies the HasEdge predicate on the "grantee" edge.
func HasGrantee() predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, GranteeTable, GranteeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasGranteeWith applies the HasEdge predicate on the "grantee" edge with a given conditions (other predicates).
func HasGranteeWith(preds ...predicate.User) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(func(s *sql.Selector) {
		step := newGranteeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GameAccountDataGrant) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GameAccountDataGrant) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GameAccountDataGrant) predicate.GameAccountDataGrant {
	return predicate.GameAccountDataGrant(sql.NotPredicates(p))
}
