// Code generated by ent, DO NOT EDIT.

package requestsranking

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the requestsranking type in the database.
	Label = "requests_ranking"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBotID holds the string denoting the bot_id field in the database.
	FieldBotID = "bot_id"
	// FieldCounts holds the string denoting the counts field in the database.
	FieldCounts = "counts"
	// Table holds the table name of the requestsranking in the database.
	Table = "requests_ranking"
)

// Columns holds all SQL columns for requestsranking fields.
var Columns = []string{
	FieldID,
	FieldBotID,
	FieldCounts,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the RequestsRanking queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBotID orders the results by the bot_id field.
func ByBotID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBotID, opts...).ToFunc()
}

// ByCounts orders the results by the counts field.
func ByCounts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCounts, opts...).ToFunc()
}
