package runtimeconfig

import (
	"bytes"
	"os"
	"reflect"
	"testing"

	json "encoding/json/v2"

	harukiRedis "github.com/Team-Haruki/Haruki-Toolbox-Backend/utils/database/redis"
)

func TestSnapshotJSONRedisRoundTrip(t *testing.T) {
	disabled := false
	for _, snapshot := range []Snapshot{
		{},
		{AllowedKeys: []string{}, WebhookEnabled: &disabled},
		{AllowedKeys: []string{"<>&\u2028\u2029", "日本語", "9007199254740993"}, PrivateAPIToken: "test-only", WebhookEnabled: &disabled},
	} {
		encoded, err := marshalSnapshot(snapshot)
		if err != nil {
			t.Fatal(err)
		}
		store, server := newRuntimeConfigRedisStore(t)
		server.Set(harukiRedis.BuildRuntimeConfigKey(), string(encoded))
		loaded, found, err := store.Load(t.Context())
		if err != nil || !found || !reflect.DeepEqual(loaded, snapshot) {
			t.Fatalf("new reader failed: found=%v err=%v", found, err)
		}
	}
}

func TestSnapshotJSONStrictDecode(t *testing.T) {
	for _, payload := range []string{
		`{"privateApiToken":"first","privateApiToken":"last"}`,
		"{\"privateApiToken\":\"\xff\"}",
	} {
		var snapshot Snapshot
		if err := unmarshalSnapshot([]byte(payload), &snapshot); err == nil {
			t.Fatal("invalid JSON accepted")
		}
	}
	snapshot := Snapshot{PrivateAPIToken: "fallback"}
	if err := unmarshalSnapshot([]byte(`{"PRIVATEAPITOKEN":"new","futureField":true}`), &snapshot); err != nil {
		t.Fatal(err)
	}
	if snapshot.PrivateAPIToken != "fallback" {
		t.Fatal("case-insensitive member accepted")
	}
}

func BenchmarkSnapshotJSON(b *testing.B) {
	snapshot := Snapshot{AllowedKeys: []string{"public-a", "public-b"}, PrivateAPIToken: "test-only", HarukiProxyUserAgent: "Haruki"}
	payload, err := marshalSnapshot(snapshot)
	if err != nil {
		b.Fatal(err)
	}
	for _, codec := range []struct {
		name      string
		marshal   func(Snapshot) ([]byte, error)
		unmarshal func([]byte, *Snapshot) error
	}{
		{"JSONv2Defaults", func(s Snapshot) ([]byte, error) { return json.Marshal(s) }, func(p []byte, s *Snapshot) error { return json.Unmarshal(p, s) }},
		{"JSONv2Snapshot", marshalSnapshot, unmarshalSnapshot},
	} {
		b.Run(codec.name+"/Marshal", func(b *testing.B) {
			b.ReportAllocs()
			for b.Loop() {
				if _, err := codec.marshal(snapshot); err != nil {
					b.Fatal(err)
				}
			}
		})
		b.Run(codec.name+"/Unmarshal", func(b *testing.B) {
			b.ReportAllocs()
			for b.Loop() {
				var s Snapshot
				if err := codec.unmarshal(payload, &s); err != nil {
					b.Fatal(err)
				}
			}
		})
	}
}

// Fixture generated by Sonic v1.15.1's native encoder on Go 1.26.0.
func TestSnapshotJSONGo126Fixture(t *testing.T) {
	payload, err := os.ReadFile("testdata/snapshot-go126-sonic.json")
	if err != nil {
		t.Fatal(err)
	}
	disabled := false
	want := Snapshot{AllowedKeys: []string{"<>&\u2028\u2029", "日本語", "9007199254740993"}, PrivateAPIToken: "test-only", WebhookEnabled: &disabled}
	var got Snapshot
	if err := unmarshalSnapshot(payload, &got); err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatal("Go 1.26 fixture decoded differently")
	}
	encoded, err := marshalSnapshot(want)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(encoded, bytes.TrimSpace(payload)) {
		t.Fatal("native Sonic wire format changed")
	}
}

// A snapshot written before the device-flow switch existed, or by an older
// binary, must read as the switch being off.
func TestOAuth2DeviceFlowSwitchMissingFieldIsOff(t *testing.T) {
	payload, err := os.ReadFile("testdata/snapshot-go126-sonic.json")
	if err != nil {
		t.Fatal(err)
	}
	var old Snapshot
	if err := unmarshalSnapshot(payload, &old); err != nil {
		t.Fatal(err)
	}
	if old.OAuth2DeviceFlowEnabled != nil || old.OAuth2DeviceFlowSwitchOn() {
		t.Fatal("an old snapshot must leave the device flow switch off")
	}
	if (Snapshot{}).OAuth2DeviceFlowSwitchOn() {
		t.Fatal("the zero snapshot must leave the device flow switch off")
	}
	// The nil switch is omitted, so the pre-existing wire format is unchanged.
	encoded, err := marshalSnapshot(old)
	if err != nil {
		t.Fatal(err)
	}
	if bytes.Contains(encoded, []byte("oauth2DeviceFlowEnabled")) {
		t.Fatalf("nil switch was serialized: %s", encoded)
	}

	for _, value := range []bool{true, false} {
		enabled := value
		encoded, err := marshalSnapshot(Snapshot{OAuth2DeviceFlowEnabled: &enabled})
		if err != nil {
			t.Fatal(err)
		}
		var decoded Snapshot
		if err := unmarshalSnapshot(encoded, &decoded); err != nil {
			t.Fatal(err)
		}
		if decoded.OAuth2DeviceFlowEnabled == nil || *decoded.OAuth2DeviceFlowEnabled != value || decoded.OAuth2DeviceFlowSwitchOn() != value {
			t.Fatalf("switch %v did not round-trip: %s", value, encoded)
		}
	}
}

func TestOAuth2DeviceFlowSwitchUpdateKeepsOtherFields(t *testing.T) {
	store, _ := newRuntimeConfigRedisStore(t)
	service := New(Snapshot{PrivateAPIToken: "seed"}, store)
	enabled := true
	if err := service.Update(t.Context(), Update{OAuth2DeviceFlowEnabled: &enabled}); err != nil {
		t.Fatal(err)
	}
	secret := "rotated"
	if err := service.Update(t.Context(), Update{WebhookJWTSecret: &secret}); err != nil {
		t.Fatal(err)
	}
	other := New(Snapshot{}, store)
	current, err := other.Current(t.Context())
	if err != nil {
		t.Fatal(err)
	}
	if !current.OAuth2DeviceFlowSwitchOn() || current.PrivateAPIToken != "seed" || current.WebhookJWTSecret != "rotated" {
		t.Fatalf("persisted snapshot = %+v", current)
	}
	// Copies never alias the stored switch.
	*current.OAuth2DeviceFlowEnabled = false
	again, _ := other.Current(t.Context())
	if !again.OAuth2DeviceFlowSwitchOn() {
		t.Fatal("Current leaked the switch pointer")
	}
}
