// Code generated by ent, DO NOT EDIT.

package riskevent

import (
	"haruki-suite/utils/database/postgresql/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLTE(FieldID, id))
}

// EventTime applies equality check predicate on the "event_time" field. It's identical to EventTimeEQ.
func EventTime(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldEventTime, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldSource, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldActorUserID, v))
}

// TargetUserID applies equality check predicate on the "target_user_id" field. It's identical to TargetUserIDEQ.
func TargetUserID(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldTargetUserID, v))
}

// IP applies equality check predicate on the "ip" field. It's identical to IPEQ.
func IP(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldIP, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldAction, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldReason, v))
}

// ResolvedAt applies equality check predicate on the "resolved_at" field. It's identical to ResolvedAtEQ.
func ResolvedAt(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedBy applies equality check predicate on the "resolved_by" field. It's identical to ResolvedByEQ.
func ResolvedBy(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldResolvedBy, v))
}

// EventTimeEQ applies the EQ predicate on the "event_time" field.
func EventTimeEQ(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldEventTime, v))
}

// EventTimeNEQ applies the NEQ predicate on the "event_time" field.
func EventTimeNEQ(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNEQ(FieldEventTime, v))
}

// EventTimeIn applies the In predicate on the "event_time" field.
func EventTimeIn(vs ...time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIn(FieldEventTime, vs...))
}

// EventTimeNotIn applies the NotIn predicate on the "event_time" field.
func EventTimeNotIn(vs ...time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotIn(FieldEventTime, vs...))
}

// EventTimeGT applies the GT predicate on the "event_time" field.
func EventTimeGT(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGT(FieldEventTime, v))
}

// EventTimeGTE applies the GTE predicate on the "event_time" field.
func EventTimeGTE(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGTE(FieldEventTime, v))
}

// EventTimeLT applies the LT predicate on the "event_time" field.
func EventTimeLT(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLT(FieldEventTime, v))
}

// EventTimeLTE applies the LTE predicate on the "event_time" field.
func EventTimeLTE(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLTE(FieldEventTime, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// SeverityEQ applies the EQ predicate on the "severity" field.
func SeverityEQ(v Severity) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldSeverity, v))
}

// SeverityNEQ applies the NEQ predicate on the "severity" field.
func SeverityNEQ(v Severity) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNEQ(FieldSeverity, v))
}

// SeverityIn applies the In predicate on the "severity" field.
func SeverityIn(vs ...Severity) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIn(FieldSeverity, vs...))
}

// SeverityNotIn applies the NotIn predicate on the "severity" field.
func SeverityNotIn(vs ...Severity) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotIn(FieldSeverity, vs...))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContainsFold(FieldSource, v))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDGT applies the GT predicate on the "actor_user_id" field.
func ActorUserIDGT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGT(FieldActorUserID, v))
}

// ActorUserIDGTE applies the GTE predicate on the "actor_user_id" field.
func ActorUserIDGTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGTE(FieldActorUserID, v))
}

// ActorUserIDLT applies the LT predicate on the "actor_user_id" field.
func ActorUserIDLT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLT(FieldActorUserID, v))
}

// ActorUserIDLTE applies the LTE predicate on the "actor_user_id" field.
func ActorUserIDLTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLTE(FieldActorUserID, v))
}

// ActorUserIDContains applies the Contains predicate on the "actor_user_id" field.
func ActorUserIDContains(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContains(FieldActorUserID, v))
}

// ActorUserIDHasPrefix applies the HasPrefix predicate on the "actor_user_id" field.
func ActorUserIDHasPrefix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasPrefix(FieldActorUserID, v))
}

// ActorUserIDHasSuffix applies the HasSuffix predicate on the "actor_user_id" field.
func ActorUserIDHasSuffix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasSuffix(FieldActorUserID, v))
}

// ActorUserIDIsNil applies the IsNil predicate on the "actor_user_id" field.
func ActorUserIDIsNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIsNull(FieldActorUserID))
}

// ActorUserIDNotNil applies the NotNil predicate on the "actor_user_id" field.
func ActorUserIDNotNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotNull(FieldActorUserID))
}

// ActorUserIDEqualFold applies the EqualFold predicate on the "actor_user_id" field.
func ActorUserIDEqualFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEqualFold(FieldActorUserID, v))
}

// ActorUserIDContainsFold applies the ContainsFold predicate on the "actor_user_id" field.
func ActorUserIDContainsFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContainsFold(FieldActorUserID, v))
}

// TargetUserIDEQ applies the EQ predicate on the "target_user_id" field.
func TargetUserIDEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldTargetUserID, v))
}

// TargetUserIDNEQ applies the NEQ predicate on the "target_user_id" field.
func TargetUserIDNEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNEQ(FieldTargetUserID, v))
}

// TargetUserIDIn applies the In predicate on the "target_user_id" field.
func TargetUserIDIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIn(FieldTargetUserID, vs...))
}

// TargetUserIDNotIn applies the NotIn predicate on the "target_user_id" field.
func TargetUserIDNotIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotIn(FieldTargetUserID, vs...))
}

// TargetUserIDGT applies the GT predicate on the "target_user_id" field.
func TargetUserIDGT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGT(FieldTargetUserID, v))
}

// TargetUserIDGTE applies the GTE predicate on the "target_user_id" field.
func TargetUserIDGTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGTE(FieldTargetUserID, v))
}

// TargetUserIDLT applies the LT predicate on the "target_user_id" field.
func TargetUserIDLT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLT(FieldTargetUserID, v))
}

// TargetUserIDLTE applies the LTE predicate on the "target_user_id" field.
func TargetUserIDLTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLTE(FieldTargetUserID, v))
}

// TargetUserIDContains applies the Contains predicate on the "target_user_id" field.
func TargetUserIDContains(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContains(FieldTargetUserID, v))
}

// TargetUserIDHasPrefix applies the HasPrefix predicate on the "target_user_id" field.
func TargetUserIDHasPrefix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasPrefix(FieldTargetUserID, v))
}

// TargetUserIDHasSuffix applies the HasSuffix predicate on the "target_user_id" field.
func TargetUserIDHasSuffix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasSuffix(FieldTargetUserID, v))
}

// TargetUserIDIsNil applies the IsNil predicate on the "target_user_id" field.
func TargetUserIDIsNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIsNull(FieldTargetUserID))
}

// TargetUserIDNotNil applies the NotNil predicate on the "target_user_id" field.
func TargetUserIDNotNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotNull(FieldTargetUserID))
}

// TargetUserIDEqualFold applies the EqualFold predicate on the "target_user_id" field.
func TargetUserIDEqualFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEqualFold(FieldTargetUserID, v))
}

// TargetUserIDContainsFold applies the ContainsFold predicate on the "target_user_id" field.
func TargetUserIDContainsFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContainsFold(FieldTargetUserID, v))
}

// IPEQ applies the EQ predicate on the "ip" field.
func IPEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldIP, v))
}

// IPNEQ applies the NEQ predicate on the "ip" field.
func IPNEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNEQ(FieldIP, v))
}

// IPIn applies the In predicate on the "ip" field.
func IPIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIn(FieldIP, vs...))
}

// IPNotIn applies the NotIn predicate on the "ip" field.
func IPNotIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotIn(FieldIP, vs...))
}

// IPGT applies the GT predicate on the "ip" field.
func IPGT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGT(FieldIP, v))
}

// IPGTE applies the GTE predicate on the "ip" field.
func IPGTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGTE(FieldIP, v))
}

// IPLT applies the LT predicate on the "ip" field.
func IPLT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLT(FieldIP, v))
}

// IPLTE applies the LTE predicate on the "ip" field.
func IPLTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLTE(FieldIP, v))
}

// IPContains applies the Contains predicate on the "ip" field.
func IPContains(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContains(FieldIP, v))
}

// IPHasPrefix applies the HasPrefix predicate on the "ip" field.
func IPHasPrefix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasPrefix(FieldIP, v))
}

// IPHasSuffix applies the HasSuffix predicate on the "ip" field.
func IPHasSuffix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasSuffix(FieldIP, v))
}

// IPIsNil applies the IsNil predicate on the "ip" field.
func IPIsNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIsNull(FieldIP))
}

// IPNotNil applies the NotNil predicate on the "ip" field.
func IPNotNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotNull(FieldIP))
}

// IPEqualFold applies the EqualFold predicate on the "ip" field.
func IPEqualFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEqualFold(FieldIP, v))
}

// IPContainsFold applies the ContainsFold predicate on the "ip" field.
func IPContainsFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContainsFold(FieldIP, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasSuffix(FieldAction, v))
}

// ActionIsNil applies the IsNil predicate on the "action" field.
func ActionIsNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIsNull(FieldAction))
}

// ActionNotNil applies the NotNil predicate on the "action" field.
func ActionNotNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotNull(FieldAction))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContainsFold(FieldAction, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContainsFold(FieldReason, v))
}

// ResolvedAtEQ applies the EQ predicate on the "resolved_at" field.
func ResolvedAtEQ(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldResolvedAt, v))
}

// ResolvedAtNEQ applies the NEQ predicate on the "resolved_at" field.
func ResolvedAtNEQ(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNEQ(FieldResolvedAt, v))
}

// ResolvedAtIn applies the In predicate on the "resolved_at" field.
func ResolvedAtIn(vs ...time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIn(FieldResolvedAt, vs...))
}

// ResolvedAtNotIn applies the NotIn predicate on the "resolved_at" field.
func ResolvedAtNotIn(vs ...time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotIn(FieldResolvedAt, vs...))
}

// ResolvedAtGT applies the GT predicate on the "resolved_at" field.
func ResolvedAtGT(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGT(FieldResolvedAt, v))
}

// ResolvedAtGTE applies the GTE predicate on the "resolved_at" field.
func ResolvedAtGTE(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGTE(FieldResolvedAt, v))
}

// ResolvedAtLT applies the LT predicate on the "resolved_at" field.
func ResolvedAtLT(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLT(FieldResolvedAt, v))
}

// ResolvedAtLTE applies the LTE predicate on the "resolved_at" field.
func ResolvedAtLTE(v time.Time) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLTE(FieldResolvedAt, v))
}

// ResolvedAtIsNil applies the IsNil predicate on the "resolved_at" field.
func ResolvedAtIsNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIsNull(FieldResolvedAt))
}

// ResolvedAtNotNil applies the NotNil predicate on the "resolved_at" field.
func ResolvedAtNotNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotNull(FieldResolvedAt))
}

// ResolvedByEQ applies the EQ predicate on the "resolved_by" field.
func ResolvedByEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEQ(FieldResolvedBy, v))
}

// ResolvedByNEQ applies the NEQ predicate on the "resolved_by" field.
func ResolvedByNEQ(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNEQ(FieldResolvedBy, v))
}

// ResolvedByIn applies the In predicate on the "resolved_by" field.
func ResolvedByIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIn(FieldResolvedBy, vs...))
}

// ResolvedByNotIn applies the NotIn predicate on the "resolved_by" field.
func ResolvedByNotIn(vs ...string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotIn(FieldResolvedBy, vs...))
}

// ResolvedByGT applies the GT predicate on the "resolved_by" field.
func ResolvedByGT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGT(FieldResolvedBy, v))
}

// ResolvedByGTE applies the GTE predicate on the "resolved_by" field.
func ResolvedByGTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldGTE(FieldResolvedBy, v))
}

// ResolvedByLT applies the LT predicate on the "resolved_by" field.
func ResolvedByLT(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLT(FieldResolvedBy, v))
}

// ResolvedByLTE applies the LTE predicate on the "resolved_by" field.
func ResolvedByLTE(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldLTE(FieldResolvedBy, v))
}

// ResolvedByContains applies the Contains predicate on the "resolved_by" field.
func ResolvedByContains(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContains(FieldResolvedBy, v))
}

// ResolvedByHasPrefix applies the HasPrefix predicate on the "resolved_by" field.
func ResolvedByHasPrefix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasPrefix(FieldResolvedBy, v))
}

// ResolvedByHasSuffix applies the HasSuffix predicate on the "resolved_by" field.
func ResolvedByHasSuffix(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldHasSuffix(FieldResolvedBy, v))
}

// ResolvedByIsNil applies the IsNil predicate on the "resolved_by" field.
func ResolvedByIsNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIsNull(FieldResolvedBy))
}

// ResolvedByNotNil applies the NotNil predicate on the "resolved_by" field.
func ResolvedByNotNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotNull(FieldResolvedBy))
}

// ResolvedByEqualFold applies the EqualFold predicate on the "resolved_by" field.
func ResolvedByEqualFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldEqualFold(FieldResolvedBy, v))
}

// ResolvedByContainsFold applies the ContainsFold predicate on the "resolved_by" field.
func ResolvedByContainsFold(v string) predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldContainsFold(FieldResolvedBy, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.RiskEvent {
	return predicate.RiskEvent(sql.FieldNotNull(FieldMetadata))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RiskEvent) predicate.RiskEvent {
	return predicate.RiskEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RiskEvent) predicate.RiskEvent {
	return predicate.RiskEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RiskEvent) predicate.RiskEvent {
	return predicate.RiskEvent(sql.NotPredicates(p))
}
