// Code generated by ent, DO NOT EDIT.

package webhooksubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the webhooksubscription type in the database.
	Label = "webhook_subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldServer holds the string denoting the server field in the database.
	FieldServer = "server"
	// FieldDataType holds the string denoting the data_type field in the database.
	FieldDataType = "data_type"
	// FieldWebhookID holds the string denoting the webhook_id field in the database.
	FieldWebhookID = "webhook_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeEndpoint holds the string denoting the endpoint edge name in mutations.
	EdgeEndpoint = "endpoint"
	// Table holds the table name of the webhooksubscription in the database.
	Table = "webhook_subscriptions"
	// EndpointTable is the table that holds the endpoint relation/edge.
	EndpointTable = "webhook_subscriptions"
	// EndpointInverseTable is the table name for the WebhookEndpoint entity.
	// It exists in this package in order to avoid circular dependency with the "webhookendpoint" package.
	EndpointInverseTable = "webhook_endpoints"
	// EndpointColumn is the table column denoting the endpoint relation/edge.
	EndpointColumn = "webhook_id"
)

// Columns holds all SQL columns for webhooksubscription fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldServer,
	FieldDataType,
	FieldWebhookID,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	UserIDValidator func(string) error
	// ServerValidator is a validator for the "server" field. It is called by the builders before save.
	ServerValidator func(string) error
	// DataTypeValidator is a validator for the "data_type" field. It is called by the builders before save.
	DataTypeValidator func(string) error
	// WebhookIDValidator is a validator for the "webhook_id" field. It is called by the builders before save.
	WebhookIDValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the WebhookSubscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByServer orders the results by the server field.
func ByServer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldServer, opts...).ToFunc()
}

// ByDataType orders the results by the data_type field.
func ByDataType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDataType, opts...).ToFunc()
}

// ByWebhookID orders the results by the webhook_id field.
func ByWebhookID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebhookID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByEndpointField orders the results by endpoint field.
func ByEndpointField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEndpointStep(), sql.OrderByField(field, opts...))
	}
}
func newEndpointStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EndpointInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, EndpointTable, EndpointColumn),
	)
}
