// Code generated by ent, DO NOT EDIT.

package webhooksubscription

import (
	"haruki-suite/utils/database/postgresql/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldUserID, v))
}

// Server applies equality check predicate on the "server" field. It's identical to ServerEQ.
func Server(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldServer, v))
}

// DataType applies equality check predicate on the "data_type" field. It's identical to DataTypeEQ.
func DataType(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldDataType, v))
}

// WebhookID applies equality check predicate on the "webhook_id" field. It's identical to WebhookIDEQ.
func WebhookID(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldWebhookID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldUserID, v))
}

// UserIDContains applies the Contains predicate on the "user_id" field.
func UserIDContains(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContains(FieldUserID, v))
}

// UserIDHasPrefix applies the HasPrefix predicate on the "user_id" field.
func UserIDHasPrefix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasPrefix(FieldUserID, v))
}

// UserIDHasSuffix applies the HasSuffix predicate on the "user_id" field.
func UserIDHasSuffix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasSuffix(FieldUserID, v))
}

// UserIDEqualFold applies the EqualFold predicate on the "user_id" field.
func UserIDEqualFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEqualFold(FieldUserID, v))
}

// UserIDContainsFold applies the ContainsFold predicate on the "user_id" field.
func UserIDContainsFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContainsFold(FieldUserID, v))
}

// ServerEQ applies the EQ predicate on the "server" field.
func ServerEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldServer, v))
}

// ServerNEQ applies the NEQ predicate on the "server" field.
func ServerNEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldServer, v))
}

// ServerIn applies the In predicate on the "server" field.
func ServerIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldServer, vs...))
}

// ServerNotIn applies the NotIn predicate on the "server" field.
func ServerNotIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldServer, vs...))
}

// ServerGT applies the GT predicate on the "server" field.
func ServerGT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldServer, v))
}

// ServerGTE applies the GTE predicate on the "server" field.
func ServerGTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldServer, v))
}

// ServerLT applies the LT predicate on the "server" field.
func ServerLT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldServer, v))
}

// ServerLTE applies the LTE predicate on the "server" field.
func ServerLTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldServer, v))
}

// ServerContains applies the Contains predicate on the "server" field.
func ServerContains(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContains(FieldServer, v))
}

// ServerHasPrefix applies the HasPrefix predicate on the "server" field.
func ServerHasPrefix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasPrefix(FieldServer, v))
}

// ServerHasSuffix applies the HasSuffix predicate on the "server" field.
func ServerHasSuffix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasSuffix(FieldServer, v))
}

// ServerEqualFold applies the EqualFold predicate on the "server" field.
func ServerEqualFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEqualFold(FieldServer, v))
}

// ServerContainsFold applies the ContainsFold predicate on the "server" field.
func ServerContainsFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContainsFold(FieldServer, v))
}

// DataTypeEQ applies the EQ predicate on the "data_type" field.
func DataTypeEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldDataType, v))
}

// DataTypeNEQ applies the NEQ predicate on the "data_type" field.
func DataTypeNEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldDataType, v))
}

// DataTypeIn applies the In predicate on the "data_type" field.
func DataTypeIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldDataType, vs...))
}

// DataTypeNotIn applies the NotIn predicate on the "data_type" field.
func DataTypeNotIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldDataType, vs...))
}

// DataTypeGT applies the GT predicate on the "data_type" field.
func DataTypeGT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldDataType, v))
}

// DataTypeGTE applies the GTE predicate on the "data_type" field.
func DataTypeGTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldDataType, v))
}

// DataTypeLT applies the LT predicate on the "data_type" field.
func DataTypeLT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldDataType, v))
}

// DataTypeLTE applies the LTE predicate on the "data_type" field.
func DataTypeLTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldDataType, v))
}

// DataTypeContains applies the Contains predicate on the "data_type" field.
func DataTypeContains(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContains(FieldDataType, v))
}

// DataTypeHasPrefix applies the HasPrefix predicate on the "data_type" field.
func DataTypeHasPrefix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasPrefix(FieldDataType, v))
}

// DataTypeHasSuffix applies the HasSuffix predicate on the "data_type" field.
func DataTypeHasSuffix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasSuffix(FieldDataType, v))
}

// DataTypeEqualFold applies the EqualFold predicate on the "data_type" field.
func DataTypeEqualFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEqualFold(FieldDataType, v))
}

// DataTypeContainsFold applies the ContainsFold predicate on the "data_type" field.
func DataTypeContainsFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContainsFold(FieldDataType, v))
}

// WebhookIDEQ applies the EQ predicate on the "webhook_id" field.
func WebhookIDEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldWebhookID, v))
}

// WebhookIDNEQ applies the NEQ predicate on the "webhook_id" field.
func WebhookIDNEQ(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldWebhookID, v))
}

// WebhookIDIn applies the In predicate on the "webhook_id" field.
func WebhookIDIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldWebhookID, vs...))
}

// WebhookIDNotIn applies the NotIn predicate on the "webhook_id" field.
func WebhookIDNotIn(vs ...string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldWebhookID, vs...))
}

// WebhookIDGT applies the GT predicate on the "webhook_id" field.
func WebhookIDGT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldWebhookID, v))
}

// WebhookIDGTE applies the GTE predicate on the "webhook_id" field.
func WebhookIDGTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldWebhookID, v))
}

// WebhookIDLT applies the LT predicate on the "webhook_id" field.
func WebhookIDLT(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldWebhookID, v))
}

// WebhookIDLTE applies the LTE predicate on the "webhook_id" field.
func WebhookIDLTE(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldWebhookID, v))
}

// WebhookIDContains applies the Contains predicate on the "webhook_id" field.
func WebhookIDContains(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContains(FieldWebhookID, v))
}

// WebhookIDHasPrefix applies the HasPrefix predicate on the "webhook_id" field.
func WebhookIDHasPrefix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasPrefix(FieldWebhookID, v))
}

// WebhookIDHasSuffix applies the HasSuffix predicate on the "webhook_id" field.
func WebhookIDHasSuffix(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldHasSuffix(FieldWebhookID, v))
}

// WebhookIDEqualFold applies the EqualFold predicate on the "webhook_id" field.
func WebhookIDEqualFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEqualFold(FieldWebhookID, v))
}

// WebhookIDContainsFold applies the ContainsFold predicate on the "webhook_id" field.
func WebhookIDContainsFold(v string) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldContainsFold(FieldWebhookID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.FieldLTE(FieldCreatedAt, v))
}

// HasEndpoint applies the HasEdge predicate on the "endpoint" edge.
func HasEndpoint() predicate.WebhookSubscription {
	return predicate.WebhookSubscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EndpointTable, EndpointColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEndpointWith applies the HasEdge predicate on the "endpoint" edge with a given conditions (other predicates).
func HasEndpointWith(preds ...predicate.WebhookEndpoint) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(func(s *sql.Selector) {
		step := newEndpointStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WebhookSubscription) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WebhookSubscription) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WebhookSubscription) predicate.WebhookSubscription {
	return predicate.WebhookSubscription(sql.NotPredicates(p))
}
