// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthorizeSocialPlatformInfo is the predicate function for authorizesocialplatforminfo builders.
type AuthorizeSocialPlatformInfo func(*sql.Selector)

// FriendLink is the predicate function for friendlink builders.
type FriendLink func(*sql.Selector)

// GameAccountBinding is the predicate function for gameaccountbinding builders.
type GameAccountBinding func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupList is the predicate function for grouplist builders.
type GroupList func(*sql.Selector)

// IOSScriptCode is the predicate function for iosscriptcode builders.
type IOSScriptCode func(*sql.Selector)

// RiskEvent is the predicate function for riskevent builders.
type RiskEvent func(*sql.Selector)

// RiskRule is the predicate function for riskrule builders.
type RiskRule func(*sql.Selector)

// SocialPlatformInfo is the predicate function for socialplatforminfo builders.
type SocialPlatformInfo func(*sql.Selector)

// SystemLog is the predicate function for systemlog builders.
type SystemLog func(*sql.Selector)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)

// TicketMessage is the predicate function for ticketmessage builders.
type TicketMessage func(*sql.Selector)

// UploadLog is the predicate function for uploadlog builders.
type UploadLog func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
