// Code generated by ent, DO NOT EDIT.

package neopg

import (
	"context"
	"haruki-suite/utils/database/neopg/commandmanifest"
	"haruki-suite/utils/database/neopg/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CommandManifestDelete is the builder for deleting a CommandManifest entity.
type CommandManifestDelete struct {
	config
	hooks    []Hook
	mutation *CommandManifestMutation
}

// Where appends a list predicates to the CommandManifestDelete builder.
func (_d *CommandManifestDelete) Where(ps ...predicate.CommandManifest) *CommandManifestDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *CommandManifestDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CommandManifestDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *CommandManifestDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(commandmanifest.Table, sqlgraph.NewFieldSpec(commandmanifest.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// CommandManifestDeleteOne is the builder for deleting a single CommandManifest entity.
type CommandManifestDeleteOne struct {
	_d *CommandManifestDelete
}

// Where appends a list predicates to the CommandManifestDelete builder.
func (_d *CommandManifestDeleteOne) Where(ps ...predicate.CommandManifest) *CommandManifestDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *CommandManifestDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{commandmanifest.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *CommandManifestDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
