// Code generated by ent, DO NOT EDIT.

package oauthclient

import (
	"haruki-suite/utils/database/postgresql/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldID, id))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientID, v))
}

// ClientSecret applies equality check predicate on the "client_secret" field. It's identical to ClientSecretEQ.
func ClientSecret(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientSecret, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldName, v))
}

// ClientType applies equality check predicate on the "client_type" field. It's identical to ClientTypeEQ.
func ClientType(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientType, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldCreatedAt, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientID, v))
}

// ClientSecretEQ applies the EQ predicate on the "client_secret" field.
func ClientSecretEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientSecret, v))
}

// ClientSecretNEQ applies the NEQ predicate on the "client_secret" field.
func ClientSecretNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientSecret, v))
}

// ClientSecretIn applies the In predicate on the "client_secret" field.
func ClientSecretIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientSecret, vs...))
}

// ClientSecretNotIn applies the NotIn predicate on the "client_secret" field.
func ClientSecretNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientSecret, vs...))
}

// ClientSecretGT applies the GT predicate on the "client_secret" field.
func ClientSecretGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientSecret, v))
}

// ClientSecretGTE applies the GTE predicate on the "client_secret" field.
func ClientSecretGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientSecret, v))
}

// ClientSecretLT applies the LT predicate on the "client_secret" field.
func ClientSecretLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientSecret, v))
}

// ClientSecretLTE applies the LTE predicate on the "client_secret" field.
func ClientSecretLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientSecret, v))
}

// ClientSecretContains applies the Contains predicate on the "client_secret" field.
func ClientSecretContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientSecret, v))
}

// ClientSecretHasPrefix applies the HasPrefix predicate on the "client_secret" field.
func ClientSecretHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientSecret, v))
}

// ClientSecretHasSuffix applies the HasSuffix predicate on the "client_secret" field.
func ClientSecretHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientSecret, v))
}

// ClientSecretEqualFold applies the EqualFold predicate on the "client_secret" field.
func ClientSecretEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientSecret, v))
}

// ClientSecretContainsFold applies the ContainsFold predicate on the "client_secret" field.
func ClientSecretContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientSecret, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldName, v))
}

// ClientTypeEQ applies the EQ predicate on the "client_type" field.
func ClientTypeEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldClientType, v))
}

// ClientTypeNEQ applies the NEQ predicate on the "client_type" field.
func ClientTypeNEQ(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldClientType, v))
}

// ClientTypeIn applies the In predicate on the "client_type" field.
func ClientTypeIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldClientType, vs...))
}

// ClientTypeNotIn applies the NotIn predicate on the "client_type" field.
func ClientTypeNotIn(vs ...string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldClientType, vs...))
}

// ClientTypeGT applies the GT predicate on the "client_type" field.
func ClientTypeGT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldClientType, v))
}

// ClientTypeGTE applies the GTE predicate on the "client_type" field.
func ClientTypeGTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldClientType, v))
}

// ClientTypeLT applies the LT predicate on the "client_type" field.
func ClientTypeLT(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldClientType, v))
}

// ClientTypeLTE applies the LTE predicate on the "client_type" field.
func ClientTypeLTE(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldClientType, v))
}

// ClientTypeContains applies the Contains predicate on the "client_type" field.
func ClientTypeContains(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContains(FieldClientType, v))
}

// ClientTypeHasPrefix applies the HasPrefix predicate on the "client_type" field.
func ClientTypeHasPrefix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasPrefix(FieldClientType, v))
}

// ClientTypeHasSuffix applies the HasSuffix predicate on the "client_type" field.
func ClientTypeHasSuffix(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldHasSuffix(FieldClientType, v))
}

// ClientTypeEqualFold applies the EqualFold predicate on the "client_type" field.
func ClientTypeEqualFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEqualFold(FieldClientType, v))
}

// ClientTypeContainsFold applies the ContainsFold predicate on the "client_type" field.
func ClientTypeContainsFold(v string) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldContainsFold(FieldClientType, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OAuthClient {
	return predicate.OAuthClient(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAuthorizations applies the HasEdge predicate on the "authorizations" edge.
func HasAuthorizations() predicate.OAuthClient {
	return predicate.OAuthClient(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AuthorizationsTable, AuthorizationsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorizationsWith applies the HasEdge predicate on the "authorizations" edge with a given conditions (other predicates).
func HasAuthorizationsWith(preds ...predicate.OAuthAuthorization) predicate.OAuthClient {
	return predicate.OAuthClient(func(s *sql.Selector) {
		step := newAuthorizationsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTokens applies the HasEdge predicate on the "tokens" edge.
func HasTokens() predicate.OAuthClient {
	return predicate.OAuthClient(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, TokensTable, TokensColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTokensWith applies the HasEdge predicate on the "tokens" edge with a given conditions (other predicates).
func HasTokensWith(preds ...predicate.OAuthToken) predicate.OAuthClient {
	return predicate.OAuthClient(func(s *sql.Selector) {
		step := newTokensStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OAuthClient) predicate.OAuthClient {
	return predicate.OAuthClient(sql.NotPredicates(p))
}
