// Code generated by ent, DO NOT EDIT.

package botsecurityalert

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Team-Haruki/Haruki-Toolbox-Backend/utils/database/postgresql/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldID, id))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldKind, v))
}

// BotID applies equality check predicate on the "bot_id" field. It's identical to BotIDEQ.
func BotID(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldBotID, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldSubject, v))
}

// SourceIP applies equality check predicate on the "source_ip" field. It's identical to SourceIPEQ.
func SourceIP(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldSourceIP, v))
}

// BuildID applies equality check predicate on the "build_id" field. It's identical to BuildIDEQ.
func BuildID(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldBuildID, v))
}

// ClientVersion applies equality check predicate on the "client_version" field. It's identical to ClientVersionEQ.
func ClientVersion(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldClientVersion, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldReason, v))
}

// Enforced applies equality check predicate on the "enforced" field. It's identical to EnforcedEQ.
func Enforced(v bool) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldEnforced, v))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldCount, v))
}

// Threshold applies equality check predicate on the "threshold" field. It's identical to ThresholdEQ.
func Threshold(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldThreshold, v))
}

// WindowSeconds applies equality check predicate on the "window_seconds" field. It's identical to WindowSecondsEQ.
func WindowSeconds(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldWindowSeconds, v))
}

// Node applies equality check predicate on the "node" field. It's identical to NodeEQ.
func Node(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldNode, v))
}

// AlertTime applies equality check predicate on the "alert_time" field. It's identical to AlertTimeEQ.
func AlertTime(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldAlertTime, v))
}

// ReceivedAt applies equality check predicate on the "received_at" field. It's identical to ReceivedAtEQ.
func ReceivedAt(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldReceivedAt, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldNote, v))
}

// HandledByUserID applies equality check predicate on the "handled_by_user_id" field. It's identical to HandledByUserIDEQ.
func HandledByUserID(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldHandledByUserID, v))
}

// HandledAt applies equality check predicate on the "handled_at" field. It's identical to HandledAtEQ.
func HandledAt(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldHandledAt, v))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContainsFold(FieldKind, v))
}

// BotIDEQ applies the EQ predicate on the "bot_id" field.
func BotIDEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldBotID, v))
}

// BotIDNEQ applies the NEQ predicate on the "bot_id" field.
func BotIDNEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldBotID, v))
}

// BotIDIn applies the In predicate on the "bot_id" field.
func BotIDIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldBotID, vs...))
}

// BotIDNotIn applies the NotIn predicate on the "bot_id" field.
func BotIDNotIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldBotID, vs...))
}

// BotIDGT applies the GT predicate on the "bot_id" field.
func BotIDGT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldBotID, v))
}

// BotIDGTE applies the GTE predicate on the "bot_id" field.
func BotIDGTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldBotID, v))
}

// BotIDLT applies the LT predicate on the "bot_id" field.
func BotIDLT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldBotID, v))
}

// BotIDLTE applies the LTE predicate on the "bot_id" field.
func BotIDLTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldBotID, v))
}

// BotIDContains applies the Contains predicate on the "bot_id" field.
func BotIDContains(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContains(FieldBotID, v))
}

// BotIDHasPrefix applies the HasPrefix predicate on the "bot_id" field.
func BotIDHasPrefix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasPrefix(FieldBotID, v))
}

// BotIDHasSuffix applies the HasSuffix predicate on the "bot_id" field.
func BotIDHasSuffix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasSuffix(FieldBotID, v))
}

// BotIDIsNil applies the IsNil predicate on the "bot_id" field.
func BotIDIsNil() predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIsNull(FieldBotID))
}

// BotIDNotNil applies the NotNil predicate on the "bot_id" field.
func BotIDNotNil() predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotNull(FieldBotID))
}

// BotIDEqualFold applies the EqualFold predicate on the "bot_id" field.
func BotIDEqualFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEqualFold(FieldBotID, v))
}

// BotIDContainsFold applies the ContainsFold predicate on the "bot_id" field.
func BotIDContainsFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContainsFold(FieldBotID, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContainsFold(FieldSubject, v))
}

// SourceIPEQ applies the EQ predicate on the "source_ip" field.
func SourceIPEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldSourceIP, v))
}

// SourceIPNEQ applies the NEQ predicate on the "source_ip" field.
func SourceIPNEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldSourceIP, v))
}

// SourceIPIn applies the In predicate on the "source_ip" field.
func SourceIPIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldSourceIP, vs...))
}

// SourceIPNotIn applies the NotIn predicate on the "source_ip" field.
func SourceIPNotIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldSourceIP, vs...))
}

// SourceIPGT applies the GT predicate on the "source_ip" field.
func SourceIPGT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldSourceIP, v))
}

// SourceIPGTE applies the GTE predicate on the "source_ip" field.
func SourceIPGTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldSourceIP, v))
}

// SourceIPLT applies the LT predicate on the "source_ip" field.
func SourceIPLT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldSourceIP, v))
}

// SourceIPLTE applies the LTE predicate on the "source_ip" field.
func SourceIPLTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldSourceIP, v))
}

// SourceIPContains applies the Contains predicate on the "source_ip" field.
func SourceIPContains(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContains(FieldSourceIP, v))
}

// SourceIPHasPrefix applies the HasPrefix predicate on the "source_ip" field.
func SourceIPHasPrefix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasPrefix(FieldSourceIP, v))
}

// SourceIPHasSuffix applies the HasSuffix predicate on the "source_ip" field.
func SourceIPHasSuffix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasSuffix(FieldSourceIP, v))
}

// SourceIPEqualFold applies the EqualFold predicate on the "source_ip" field.
func SourceIPEqualFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEqualFold(FieldSourceIP, v))
}

// SourceIPContainsFold applies the ContainsFold predicate on the "source_ip" field.
func SourceIPContainsFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContainsFold(FieldSourceIP, v))
}

// BuildIDEQ applies the EQ predicate on the "build_id" field.
func BuildIDEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldBuildID, v))
}

// BuildIDNEQ applies the NEQ predicate on the "build_id" field.
func BuildIDNEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldBuildID, v))
}

// BuildIDIn applies the In predicate on the "build_id" field.
func BuildIDIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldBuildID, vs...))
}

// BuildIDNotIn applies the NotIn predicate on the "build_id" field.
func BuildIDNotIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldBuildID, vs...))
}

// BuildIDGT applies the GT predicate on the "build_id" field.
func BuildIDGT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldBuildID, v))
}

// BuildIDGTE applies the GTE predicate on the "build_id" field.
func BuildIDGTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldBuildID, v))
}

// BuildIDLT applies the LT predicate on the "build_id" field.
func BuildIDLT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldBuildID, v))
}

// BuildIDLTE applies the LTE predicate on the "build_id" field.
func BuildIDLTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldBuildID, v))
}

// BuildIDContains applies the Contains predicate on the "build_id" field.
func BuildIDContains(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContains(FieldBuildID, v))
}

// BuildIDHasPrefix applies the HasPrefix predicate on the "build_id" field.
func BuildIDHasPrefix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasPrefix(FieldBuildID, v))
}

// BuildIDHasSuffix applies the HasSuffix predicate on the "build_id" field.
func BuildIDHasSuffix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasSuffix(FieldBuildID, v))
}

// BuildIDEqualFold applies the EqualFold predicate on the "build_id" field.
func BuildIDEqualFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEqualFold(FieldBuildID, v))
}

// BuildIDContainsFold applies the ContainsFold predicate on the "build_id" field.
func BuildIDContainsFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContainsFold(FieldBuildID, v))
}

// ClientVersionEQ applies the EQ predicate on the "client_version" field.
func ClientVersionEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldClientVersion, v))
}

// ClientVersionNEQ applies the NEQ predicate on the "client_version" field.
func ClientVersionNEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldClientVersion, v))
}

// ClientVersionIn applies the In predicate on the "client_version" field.
func ClientVersionIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldClientVersion, vs...))
}

// ClientVersionNotIn applies the NotIn predicate on the "client_version" field.
func ClientVersionNotIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldClientVersion, vs...))
}

// ClientVersionGT applies the GT predicate on the "client_version" field.
func ClientVersionGT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldClientVersion, v))
}

// ClientVersionGTE applies the GTE predicate on the "client_version" field.
func ClientVersionGTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldClientVersion, v))
}

// ClientVersionLT applies the LT predicate on the "client_version" field.
func ClientVersionLT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldClientVersion, v))
}

// ClientVersionLTE applies the LTE predicate on the "client_version" field.
func ClientVersionLTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldClientVersion, v))
}

// ClientVersionContains applies the Contains predicate on the "client_version" field.
func ClientVersionContains(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContains(FieldClientVersion, v))
}

// ClientVersionHasPrefix applies the HasPrefix predicate on the "client_version" field.
func ClientVersionHasPrefix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasPrefix(FieldClientVersion, v))
}

// ClientVersionHasSuffix applies the HasSuffix predicate on the "client_version" field.
func ClientVersionHasSuffix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasSuffix(FieldClientVersion, v))
}

// ClientVersionEqualFold applies the EqualFold predicate on the "client_version" field.
func ClientVersionEqualFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEqualFold(FieldClientVersion, v))
}

// ClientVersionContainsFold applies the ContainsFold predicate on the "client_version" field.
func ClientVersionContainsFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContainsFold(FieldClientVersion, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContainsFold(FieldReason, v))
}

// EnforcedEQ applies the EQ predicate on the "enforced" field.
func EnforcedEQ(v bool) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldEnforced, v))
}

// EnforcedNEQ applies the NEQ predicate on the "enforced" field.
func EnforcedNEQ(v bool) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldEnforced, v))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldCount, v))
}

// ThresholdEQ applies the EQ predicate on the "threshold" field.
func ThresholdEQ(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldThreshold, v))
}

// ThresholdNEQ applies the NEQ predicate on the "threshold" field.
func ThresholdNEQ(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldThreshold, v))
}

// ThresholdIn applies the In predicate on the "threshold" field.
func ThresholdIn(vs ...int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldThreshold, vs...))
}

// ThresholdNotIn applies the NotIn predicate on the "threshold" field.
func ThresholdNotIn(vs ...int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldThreshold, vs...))
}

// ThresholdGT applies the GT predicate on the "threshold" field.
func ThresholdGT(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldThreshold, v))
}

// ThresholdGTE applies the GTE predicate on the "threshold" field.
func ThresholdGTE(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldThreshold, v))
}

// ThresholdLT applies the LT predicate on the "threshold" field.
func ThresholdLT(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldThreshold, v))
}

// ThresholdLTE applies the LTE predicate on the "threshold" field.
func ThresholdLTE(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldThreshold, v))
}

// WindowSecondsEQ applies the EQ predicate on the "window_seconds" field.
func WindowSecondsEQ(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldWindowSeconds, v))
}

// WindowSecondsNEQ applies the NEQ predicate on the "window_seconds" field.
func WindowSecondsNEQ(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldWindowSeconds, v))
}

// WindowSecondsIn applies the In predicate on the "window_seconds" field.
func WindowSecondsIn(vs ...int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldWindowSeconds, vs...))
}

// WindowSecondsNotIn applies the NotIn predicate on the "window_seconds" field.
func WindowSecondsNotIn(vs ...int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldWindowSeconds, vs...))
}

// WindowSecondsGT applies the GT predicate on the "window_seconds" field.
func WindowSecondsGT(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldWindowSeconds, v))
}

// WindowSecondsGTE applies the GTE predicate on the "window_seconds" field.
func WindowSecondsGTE(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldWindowSeconds, v))
}

// WindowSecondsLT applies the LT predicate on the "window_seconds" field.
func WindowSecondsLT(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldWindowSeconds, v))
}

// WindowSecondsLTE applies the LTE predicate on the "window_seconds" field.
func WindowSecondsLTE(v int64) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldWindowSeconds, v))
}

// NodeEQ applies the EQ predicate on the "node" field.
func NodeEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldNode, v))
}

// NodeNEQ applies the NEQ predicate on the "node" field.
func NodeNEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldNode, v))
}

// NodeIn applies the In predicate on the "node" field.
func NodeIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldNode, vs...))
}

// NodeNotIn applies the NotIn predicate on the "node" field.
func NodeNotIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldNode, vs...))
}

// NodeGT applies the GT predicate on the "node" field.
func NodeGT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldNode, v))
}

// NodeGTE applies the GTE predicate on the "node" field.
func NodeGTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldNode, v))
}

// NodeLT applies the LT predicate on the "node" field.
func NodeLT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldNode, v))
}

// NodeLTE applies the LTE predicate on the "node" field.
func NodeLTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldNode, v))
}

// NodeContains applies the Contains predicate on the "node" field.
func NodeContains(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContains(FieldNode, v))
}

// NodeHasPrefix applies the HasPrefix predicate on the "node" field.
func NodeHasPrefix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasPrefix(FieldNode, v))
}

// NodeHasSuffix applies the HasSuffix predicate on the "node" field.
func NodeHasSuffix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasSuffix(FieldNode, v))
}

// NodeEqualFold applies the EqualFold predicate on the "node" field.
func NodeEqualFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEqualFold(FieldNode, v))
}

// NodeContainsFold applies the ContainsFold predicate on the "node" field.
func NodeContainsFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContainsFold(FieldNode, v))
}

// AlertTimeEQ applies the EQ predicate on the "alert_time" field.
func AlertTimeEQ(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldAlertTime, v))
}

// AlertTimeNEQ applies the NEQ predicate on the "alert_time" field.
func AlertTimeNEQ(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldAlertTime, v))
}

// AlertTimeIn applies the In predicate on the "alert_time" field.
func AlertTimeIn(vs ...time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldAlertTime, vs...))
}

// AlertTimeNotIn applies the NotIn predicate on the "alert_time" field.
func AlertTimeNotIn(vs ...time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldAlertTime, vs...))
}

// AlertTimeGT applies the GT predicate on the "alert_time" field.
func AlertTimeGT(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldAlertTime, v))
}

// AlertTimeGTE applies the GTE predicate on the "alert_time" field.
func AlertTimeGTE(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldAlertTime, v))
}

// AlertTimeLT applies the LT predicate on the "alert_time" field.
func AlertTimeLT(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldAlertTime, v))
}

// AlertTimeLTE applies the LTE predicate on the "alert_time" field.
func AlertTimeLTE(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldAlertTime, v))
}

// ReceivedAtEQ applies the EQ predicate on the "received_at" field.
func ReceivedAtEQ(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldReceivedAt, v))
}

// ReceivedAtNEQ applies the NEQ predicate on the "received_at" field.
func ReceivedAtNEQ(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldReceivedAt, v))
}

// ReceivedAtIn applies the In predicate on the "received_at" field.
func ReceivedAtIn(vs ...time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldReceivedAt, vs...))
}

// ReceivedAtNotIn applies the NotIn predicate on the "received_at" field.
func ReceivedAtNotIn(vs ...time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldReceivedAt, vs...))
}

// ReceivedAtGT applies the GT predicate on the "received_at" field.
func ReceivedAtGT(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldReceivedAt, v))
}

// ReceivedAtGTE applies the GTE predicate on the "received_at" field.
func ReceivedAtGTE(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldReceivedAt, v))
}

// ReceivedAtLT applies the LT predicate on the "received_at" field.
func ReceivedAtLT(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldReceivedAt, v))
}

// ReceivedAtLTE applies the LTE predicate on the "received_at" field.
func ReceivedAtLTE(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldReceivedAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldStatus, vs...))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContainsFold(FieldNote, v))
}

// HandledByUserIDEQ applies the EQ predicate on the "handled_by_user_id" field.
func HandledByUserIDEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldHandledByUserID, v))
}

// HandledByUserIDNEQ applies the NEQ predicate on the "handled_by_user_id" field.
func HandledByUserIDNEQ(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldHandledByUserID, v))
}

// HandledByUserIDIn applies the In predicate on the "handled_by_user_id" field.
func HandledByUserIDIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldHandledByUserID, vs...))
}

// HandledByUserIDNotIn applies the NotIn predicate on the "handled_by_user_id" field.
func HandledByUserIDNotIn(vs ...string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldHandledByUserID, vs...))
}

// HandledByUserIDGT applies the GT predicate on the "handled_by_user_id" field.
func HandledByUserIDGT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldHandledByUserID, v))
}

// HandledByUserIDGTE applies the GTE predicate on the "handled_by_user_id" field.
func HandledByUserIDGTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldHandledByUserID, v))
}

// HandledByUserIDLT applies the LT predicate on the "handled_by_user_id" field.
func HandledByUserIDLT(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldHandledByUserID, v))
}

// HandledByUserIDLTE applies the LTE predicate on the "handled_by_user_id" field.
func HandledByUserIDLTE(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldHandledByUserID, v))
}

// HandledByUserIDContains applies the Contains predicate on the "handled_by_user_id" field.
func HandledByUserIDContains(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContains(FieldHandledByUserID, v))
}

// HandledByUserIDHasPrefix applies the HasPrefix predicate on the "handled_by_user_id" field.
func HandledByUserIDHasPrefix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasPrefix(FieldHandledByUserID, v))
}

// HandledByUserIDHasSuffix applies the HasSuffix predicate on the "handled_by_user_id" field.
func HandledByUserIDHasSuffix(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldHasSuffix(FieldHandledByUserID, v))
}

// HandledByUserIDIsNil applies the IsNil predicate on the "handled_by_user_id" field.
func HandledByUserIDIsNil() predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIsNull(FieldHandledByUserID))
}

// HandledByUserIDNotNil applies the NotNil predicate on the "handled_by_user_id" field.
func HandledByUserIDNotNil() predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotNull(FieldHandledByUserID))
}

// HandledByUserIDEqualFold applies the EqualFold predicate on the "handled_by_user_id" field.
func HandledByUserIDEqualFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEqualFold(FieldHandledByUserID, v))
}

// HandledByUserIDContainsFold applies the ContainsFold predicate on the "handled_by_user_id" field.
func HandledByUserIDContainsFold(v string) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldContainsFold(FieldHandledByUserID, v))
}

// HandledAtEQ applies the EQ predicate on the "handled_at" field.
func HandledAtEQ(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldEQ(FieldHandledAt, v))
}

// HandledAtNEQ applies the NEQ predicate on the "handled_at" field.
func HandledAtNEQ(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNEQ(FieldHandledAt, v))
}

// HandledAtIn applies the In predicate on the "handled_at" field.
func HandledAtIn(vs ...time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIn(FieldHandledAt, vs...))
}

// HandledAtNotIn applies the NotIn predicate on the "handled_at" field.
func HandledAtNotIn(vs ...time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotIn(FieldHandledAt, vs...))
}

// HandledAtGT applies the GT predicate on the "handled_at" field.
func HandledAtGT(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGT(FieldHandledAt, v))
}

// HandledAtGTE applies the GTE predicate on the "handled_at" field.
func HandledAtGTE(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldGTE(FieldHandledAt, v))
}

// HandledAtLT applies the LT predicate on the "handled_at" field.
func HandledAtLT(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLT(FieldHandledAt, v))
}

// HandledAtLTE applies the LTE predicate on the "handled_at" field.
func HandledAtLTE(v time.Time) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldLTE(FieldHandledAt, v))
}

// HandledAtIsNil applies the IsNil predicate on the "handled_at" field.
func HandledAtIsNil() predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldIsNull(FieldHandledAt))
}

// HandledAtNotNil applies the NotNil predicate on the "handled_at" field.
func HandledAtNotNil() predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.FieldNotNull(FieldHandledAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.BotSecurityAlert) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.BotSecurityAlert) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.BotSecurityAlert) predicate.BotSecurityAlert {
	return predicate.BotSecurityAlert(sql.NotPredicates(p))
}
